### ISSUE TITLE
Submission: DataSpaceR

### ISSUE THREAD

**Issue by juyeongkim** [ropensci/software-review#261]
### Summary

-   What does this package do? (explain in 50 words or less):
DataSpaceR is an R interface to the CAVD DataSpace, a data sharing and discovery tool that facilitates exploration of HIV immunological data from pre-clinical and clinical HIV vaccine studies.

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: DataSpaceR
Type: Package
Title: An R Interface to the CAVD DataSpace
Version: 0.5.2
Authors@R: c(person("Ju Yeong", "Kim",
                    email = "jkim2345@fredhutch.org",
                    role = c("aut", "cre")),
             person("The Collaboration for AIDS Vaccine Discovery",
                    role = "cph"))
Description: Provides a convenient API for accessing datasets within
    the CAVD DataSpace (dataspace.cavd.org).
URL: https://github.com/CAVDDataSpace/DataSpaceR
BugReports: https://github.com/CAVDDataSpace/DataSpaceR/issues
License: GPL-3 + file LICENSE
Encoding: UTF-8
LazyData: true
Imports:
    utils,
    R6,
    Rlabkey (>= 2.2.0),
    curl,
    httr,
    assertthat,
    digest,
    rjson,
    data.table
Suggests:
    testthat,
    covr,
    knitr,
    pryr
VignetteBuilder: knitr
RoxygenNote: 6.1.0
```

-   URL for the package (the development repository, not a stylized html page):
https://github.com/CAVDDataSpace/DataSpaceR

- Please indicate which category or categories from our [package fit policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) this package falls under ***and why**(? (e.g., data retrieval, reproducibility. If you are unsure, we suggest you make a pre-submission inquiry.):

[e.g., "data extraction, because the package parses a scientific data file format"]

The package fits into the **data retrieval** category as it provides API access to the database.

-   Who is the target audience and what are scientific applications of this package?  

The target audience are immunologists, bioinformaticians, or statisticians in HIV vaccine research, and the scientific applications are meta analyses of exploring relationships across assays, studies, and time.

-   Are there other R packages that accomplish the same thing? If so, how does
yours differ or meet [our criteria for best-in-category](https://github.com/ropensci/onboarding/blob/master/policies.md#overlap)?

None that I am aware of.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

https://github.com/ropensci/onboarding/issues/260

### Requirements

Confirm each of the following by checking the box.  This package:

- [x] does not violate the Terms of Service of any service it interacts with. 
- [x] has a CRAN and OSI accepted license.
- [x] contains a README with instructions for installing the development version. 
- [x] includes documentation with examples for all functions.
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a test suite.
- [x] has continuous integration, including reporting of test coverage, using services such as Travis CI, Coveralls and/or CodeCov.
- [x] I agree to abide by [ROpenSci's Code of Conduct](https://github.com/ropensci/onboarding/blob/master/policies.md#code-of-conduct) during the review process and in maintaining my package should it be accepted.

#### Publication options

- [x] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:
    - [ ] The package has an **obvious research application** according to [JOSS's definition](http://joss.theoj.org/about#submission_requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](http://joss.theoj.org/about#paper_structure) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)
- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:
    - [ ] The package is novel and will be of interest to the broad readership of the journal. 
    - [ ] The manuscript describing the package is no longer than 3000 words.
    - [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
    - (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
    - (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
    - (*Please do not submit your package separately to Methods in Ecology and Evolution*)

### Detail

- [x] Does `R CMD check` (or `devtools::check()`) succeed?  Paste and describe any errors or warnings:

- [ ] Does the package conform to [rOpenSci packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)? Please describe any exceptions:
  - I've used camelCase in this package.
  - The test coverage is currently 92%, and I am getting LaTex errors with `goodpractice`:
```R
── GP DataSpaceR ────────────────────────────────────────────────────────────────────────────────

It is good practice to

  ✖ write unit tests for all functions, and all package code in general. 92%
    of code lines are covered by test cases.

    R/DataSpaceConnection.R:161:NA
    R/helpers.R:29:NA
    R/helpers.R:49:NA
    R/helpers.R:52:NA
    R/helpers.R:152:NA
    ... and 34 more lines

  ✖ fix this R CMD check WARNING: LaTeX errors when creating PDF version.
    This typically indicates Rd problems. LaTeX errors found: ! LaTeX Error: File
    `inconsolata.sty' not found. Type X to quit or <RETURN> to proceed, or enter new
    name. (Default extension: sty)
─────────────────────────────────────────────────────────────────────────────────────────────────
```

- If this is a resubmission following rejection, please explain the change in circumstances:

- If possible, please provide recommendations of reviewers - those with experience with similar packages and/or likely users of your package - and their GitHub user names:
@seaaan

**Comment by sckott** [comment]
Thanks for your submission @juyeongkim We'll get back to you very soon

**Comment by noamross** [comment]
### Editor checks:

- [x] **Fit**: The package meets criteria for [fit](policies.md#fit) and [overlap](policies.md#fit)
- [x] **Automated tests:** Package has a testing suite and is tested via Travis-CI or another CI service.
- [x] **License:** The package has a CRAN or OSI accepted license
- [x] **Repository:** The repository link resolves correctly
- [ ] **Archive** (JOSS only, may be post-review): The repository DOI resolves correctly
- [ ] **Version** (JOSS only, may be post-review): Does the release version given match the GitHub release (v1.0.0)?

---

#### Editor comments

Thanks for your submission @juyeongkim and sorry for being a little slow on the pick-up.  What a neat package design!  Unfortunately I'm getting a few errors while testing.  In R CMD Check, I get:

```
* creating vignettes ... ERROR
Quitting from lines 146-148 (Intro_to_DataSpaceR.Rmd) 
Error: processing vignette 'Intro_to_DataSpaceR.Rmd' failed with diagnostics:
216 is not a valid group ID
Execution halted
Error: Command failed (1)
Execution halted
```

And running `test_package`, I get:

```
Loading DataSpaceR
Loading required package: testthat
By exporting data from the CAVD DataSpace, you agree to be bound by the Terms of Use available on the CAVD DataSpace sign-in page at https://dataspace.cavd.org/cds/CAVD/app.view?
Testing DataSpaceR
✔ | OK F W S | Context
✔ | 40       | DataSpaceConnection [7.6 s]
✖ | 19 1     | helpers [1.1 s]
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test-helpers.R:21: failure: `getUserEmail`
DataSpaceR:::getUserEmail(url, NULL) not equal to `email`.
1/1 mismatches
x[1]: "noam.ross@gmail.com"
y[1]: "jkim2345@scharp.org"
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ |  9       | netrc
✔ | 73       | DataSpaceStudy (CAVD) [191.7 s]
✔ | 64       | DataSpaceStudy (cvd408) [9.2 s]
✖ |  0 2     | DataSpaceStudy (mice)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test-study.R:26: failure: can connect to studies
`cavd` inherits from `try-error` not `DataSpaceStudy`.

test-study.R:27: failure: can connect to studies
`cavd` inherits from `try-error` not `R6`.
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ |  0 2     | DataSpaceStudy (CAVD 242)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test-study.R:26: failure: can connect to studies
`cavd` inherits from `try-error` not `DataSpaceStudy`.

test-study.R:27: failure: can connect to studies
`cavd` inherits from `try-error` not `R6`.
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ | 73       | DataSpaceStudy (NYVAC durability comparison) [67.8 s]

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 280.0 s

OK:       278
Failed:   5
Warnings: 0
Skipped:  0
```

I note that in the neither in web GUI nor in `con$availableGroups` do I see group 216.  I suspect that I don't have the same permissions you do and that your tests and vignettes attempting to access studies not available to all users. (I see the first test failure is because you've hard-coded your email into the tests, so it doesn't work once I've made my own netrc file). If this is the case, you should probably either select a different subset of studies, or skip tests conditionally based on user permissions.

Everything else checks out fairly well, though, so I'm happy to start seeking reviewers while you patch this.
---

Reviewers:
Due date:

**Comment by juyeongkim** [comment]
Thanks @noamross! I will fix these tests today.

**Comment by noamross** [comment]
Reviewers assigned: @seaaan and @czibman. Due date 2018-11-26.

**Comment by noamross** [comment]
Thanks for your thorough review, @seaaan! @juyeongkim, I suggest waiting for @czibman's review so you can address comments together.

**Comment by czibman** [comment]
DataSpaceR review
================

## Package Review

*Please check off boxes as applicable, and elaborate in comments below.
Your review is not limited to these topics, as described in the reviewer
guide*

  - \[x\] As the reviewer I confirm that there are no conflicts of
    interest for me to review this work (If you are unsure whether you
    are in conflict, please speak to your editor *before* starting your
    review).

#### Documentation

The package includes all the following forms of documentation:

  - \[x\] **A statement of need** clearly stating problems the software
    is designed to solve and its target audience in README
  - \[x\] **Installation instructions:** for the development version of
    package and any non-standard dependencies in README
  - \[x\] **Vignette(s)** demonstrating major functionality that runs
    successfully locally
  - \[x\] **Function Documentation:** for all exported functions in R
    help
  - \[x\] **Examples** for all exported functions in R Help that run
    successfully locally
  - \[x\] **Community guidelines** including contribution guidelines in
    the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports`
    and `Maintainer` (which may be autogenerated via `Authors@R`).

##### For packages co-submitting to JOSS

N/A

#### Functionality

  - \[x\] **Installation:** Installation succeeds as documented.
  - \[x\] **Functionality:** Any functional claims of the software been
    confirmed.
  - \[x\] **Performance:** Any performance claims of the software been
    confirmed.
  - \[x\] **Automated tests:** Unit tests cover essential functions of
    the package and a reasonable range of inputs and conditions. All
    tests pass on the local machine.
  - \[x\] **Packaging guidelines**: The package conforms to the rOpenSci
    packaging guidelines

#### Final approval (post-review)

  - \[ \] **The author has responded to my review and made changes to my
    satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 8 —

### Review Comments

#### Summary

Thank you so much for making these data more accessible to researchers
This appears to be a well-designed package. I note below where some
improvements can be make the use of this package more dummy-proof.

#### README

Per ROpenSci’s requirement that the Statement of Need specify the user
population, consider adding a line or two about who a typical user of
the CAVD data might be.

Please also consider more explicitly describing contribution guidelines
in the README (in keeping with the “Community Guidelines” Requirement).

#### Installation

I had to use “force = TRUE” to get the package to
    load.

``` r
devtools::install_github("CAVDDataSpace/DataSpaceR")
```

    ## Skipping install of 'DataSpaceR' from a github remote, the SHA1 (a139df3d) has not changed since last install.
    ##   Use `force = TRUE` to force installation

#### Creation of CAVD account

The package creator instructs the user for a CAVD account at
<https://dataspace.cavd.org>. I recognize that the registration process
is beyond the influence of the package creator, but registering for a
CAVD account was tricky since, when I clicked “submit” on the “member
details” page, nothing happened. Submitting member details appears
optional, however.

#### Vignette

Note that, when loading the package, a statement appears reminding the
user of the Terms of Use. That’s fine, but it ends in a question mark
(that is part of the url name). Makes me think I’m being prompted for
something. This can be reworded as “see \[url\] for the
    terms”.

``` r
library(DataSpaceR)
```

    ## By exporting data from the CAVD DataSpace, you agree to be bound by the Terms of Use available on the CAVD DataSpace sign-in page at https://dataspace.cavd.org/cds/CAVD/app.view?

The Vignette has the reader look at the list of available groups and
choose group 216. There is no group 216 (see below). Is this because the
group was deleted from the CAVD dataset? Is there a way to ensure that
the documentation for this package stays current when the dataset
changes?

``` r
knitr::kable(con$availableGroups)
```

|  id | label                              | originalLabel                      | description                                                                                                               | createdBy | shared |   n | studies                                   |
| --: | :--------------------------------- | :--------------------------------- | :------------------------------------------------------------------------------------------------------------------------ | :-------- | :----- | --: | :---------------------------------------- |
| 220 | NYVAC durability comparison        | NYVAC\_durability                  | Compare durability in 4 NHP studies using NYVAC-C (vP2010) and NYVAC-KC-gp140 (ZM96) products.                            | ehenrich  | TRUE   |  78 | c(“cvd281”, “cvd434”, “cvd259”, “cvd277”) |
| 228 | HVTN 505 case control subjects     | HVTN 505 case control subjects     | Participants from HVTN 505 included in the case-control analysis                                                          | drienna   | TRUE   | 189 | vtn505                                    |
| 230 | HVTN 505 polyfunctionality vs BAMA | HVTN 505 polyfunctionality vs BAMA | Compares ICS polyfunctionality (CD8+, Any Env) to BAMA mfi-delta (single Env antigen) in the HVTN 505 case control cohort | drienna   | TRUE   | 170 | vtn505                                    |

I was able to follow the rest of the vignette without trouble. As a very
minor quibble, the vignette reference at least one other package
(`pryr`). To allow for a faster run through the vignette that can be
done entirely by cutting and pasting, it would be helpful to add code in
the vignette to install any referenced packages if the user has not
already (as in below).

``` r
if (!("pryr" %in% installed.packages())) install.packages("pryr")
```

#### Documentation and testing

The package includes 3 functions: writeNetrc, checkNetrc, and connectDS.
Help files are provided for:

  - DataSpaceConnection
  - DataSpaceR-package
  - DataSpaceStudy
  - checkNetrc
  - connectDS
  - writeNetrc

The “DataSpaceR-package” help file does not appear to be loading
correctly when I type `?DataSpaceR-package`(I get the help file for
Arithmetic Operators instead).

All three function help files include examples. The information in the
README and vignette on creating a .netrc file is helpful. The help file
for the `writeNetrc` function, in contrast, could benefit from
containing more of the information that is in the vignette (for example
on how to create and save the file). In addition, it would be helpful if
the `writeNetrc` command provided the option to overwrite an existing
netrc file (finding and changing a file with a non-standard name was
harder than it should have been on my mac).

There are four files containing tests:

  - test-connection.R

  - test-helpers.R

  - test-netrc.R

  - test-study.R

#### Additional comments:

It’s not clear to me what the purpose of a group is. I would have
thought it was a group of studies, but it is a group of datasets.

When you connect, you are provided with information regarding the number
of studies, subjects, assays, datapoints, and groups in the CAVD
database. It would be helpful if the documentation explained the role of
the five assays and why the number of assays is a meaningful number to
report (unless this information is obvious to people who’d use this
data). Perhaps also report the number of datasets.

**Comment by juyeongkim** [comment]
Thanks for your feedback, @seaaan and @czibman! I will address your reviews later this week.

**Comment by juyeongkim** [comment]
Thank you @seaaan and @czibman for reviewing the package!

**Comment by seaaan** [comment]
Nice changes! Sorry it took me a bit to get a chance to review them. The updated package builds fine and passes R CMD CHECK. I have a few minor comments--and I do encourage you to consult with users about changing the interface as discussed above--but other than those, I don't have anything else and I approve the package. Nice job!

## Vignette: how to get help
I suggest adding a short section in the vignette (and possibly README) explaining how to access documentation, since the help for R6 classes works a bit differently than for most of R. 

## Reference tables
For the reference tables of the vignette, add a little explanatory text explaining what the reference tables are meant to be used for. 

Also, I suggest dropping a number of little-used methods from the tables. This will make the tables more useful for finding the most commonly used functions. Specifically, for `DataSpaceConnection`: drop `config`, `initialize`, `print`, and possibly `refresh`; for `DataSpaceStudy`: drop `study`, `group`, `config`, `cache`, `clearCache`, `initialize`, `print`, and possibly `refresh`. 

I don't think you need the "type" column in these tables.

**Comment by juyeongkim** [comment]
@seaaan Thanks! I made the changes [here](https://github.com/CAVDDataSpace/DataSpaceR/commit/b1ec75a6e1ccfce5f50f454b392a82312f4c8941).

Happy new year! :fireworks: :champagne:

**Comment by czibman** [comment]
Apologies for taking so long to look at this.  I don't have any further comments.  Thanks @juyeongkim again for making this package, and happy new year to you all as well!

**Comment by juyeongkim** [comment]
Thank you @czibman!

**Comment by juyeongkim** [comment]
Ping @noamross

**Comment by juyeongkim** [comment]
@noamross Awesome! 🍾 

I've checked off everything in the to-do list:
[x] Transfer the repo to rOpenSci
[x] Add the rOpenSci header to README
[x] Fix links
[x] Add codemeta.json

I'd like to acknowledge my reviewers in my package DESCRIPTION and/or README. Would you like to be acknowledged, @seaaan and @czibman?

I would love to write a blog post about my package. (I still need to write blog posts on RSelenium...)

Thank you @noamross, @seaaan, and @czibman for the review and feedback. It's been undoubtedly productive. 💯

**Comment by seaaan** [comment]
Sure!

**Comment by stefaniebutland** [comment]
> I would love to write a blog post about my package

woohoo! 
- Blog posts by authors of peer-reviewed packages so you can get an idea of narrative style and length you prefer: https://ropensci.org/tags/software-peer-review/ 
- Tech Notes: https://ropensci.org/technotes/
- Technical and editorial guidelines: https://github.com/ropensci/roweb2#contributing-a-blog-post

Give me an idea of when you would like to submit a draft via pull request. Don't worry about the RSelenium posts - would love to have one but there's no obligation and you could do one any time it works for you. 

Happy to answer any questions @juyeongkim.

**Comment by stefaniebutland** [comment]
@juyeongkim following up. I know it's 💯hard to do all the work AND write a post. We would really love to help get more eyes on your work but I don't want to bug you. Let me know if you want me to pester you about scheduling a post of your choice.
