### ISSUE TITLE
Presubmission inquiry: tmhmm

### ISSUE THREAD

**Issue by richelbilderbeek** [ropensci/software-review#276]
Submitting Author: Richel J.C. Bilderbeek (@richelbilderbeek)  
Repository: https://github.com/richelbilderbeek/tmhmm

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: tmhmm
Type: Package
Title: Call TMHMM from R
Version: 1.0
Author: Richel J.C. Bilderbeek
Maintainer: Richel J.C. Bilderbeek <richel@richelbilderbeek.nl>
Description: 
  'TMHMM' is a program to predict transmembrane helices in proteins. 
  'TMHMM' can be called from a website and/or locally using Bash. 
  This package allows to install and call TMHMM from R and parse its results.
License: GPL-3 | file LICENSE
Encoding: UTF-8
LazyData: true
Imports:
    rappdirs,
    stringr,
    testit
Suggests: 
    testthat,
    knitr,
    rmarkdown
URL: https://github.com/richelbilderbeek/tmhmm
BugReports: https://github.com/richelbilderbeek/tmhmm/issues
RoxygenNote: 6.1.1
VignetteBuilder: knitr
```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below.:

	- [ ] data retrieval
	- [x] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how the and why the package falls under these categories (briefly, 1-2 sentences).  Please note any areas you are unsure of:

The package allows the user to call the tool 'TMHMM' from R,
so it extracts the results from that tool.

-   Who is the target audience and what are scientific applications of this package?  

Bioinformaticians that use 'TMHMM'. It's used to determine the location (inside,
outside, in the membrane) of amino acids in a membrane protein.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No.

-  Any other questions or issues we should be aware of?:

I am unsure about the compatibility between 'TMHMM' and rOpenSci guidelines.

'TMHMM', at [its download page](http://www.cbs.dtu.dk/cgi-bin/nph-sw_request?tmhmm) 
is very clear:

> Please note that this page is intended for academic users only. 

'TMHMM' ensures that its users are academic users, as they have to fill
in a form [at the download page](http://www.cbs.dtu.dk/cgi-bin/nph-sw_request?tmhmm)
in which they have to specify their academic role. If the user passes this, he/she
obtains a download URL that expires.

To ensure not to hurt 'TMHMM' policy, the users of this package must
specify such an obtained download URL.

So, although the package in its current forms plays nicely with 'TMHMM',
I am unsure if this way is compatible with the rOpenSci guidelines.
I feel it does, but I'll submit the package after confirmation of this.

**Comment by sckott** [comment]
thanks for your inquiry @richelbilderbeek Editors will discuss and get back to you

**Comment by sckott** [comment]
We just saw https://github.com/dansondergaard/tmhmm.py  which is a separate implementation, and so doesn't require the command line utility. Have you considered wrapping it with [reticulate](https://cran.rstudio.com/web/packages/reticulate/)? I don't know if it will work since the python lib has C code, but seems worth a try. If it works and if it means your pkg works on all platforms, and doesn't require the academic only gate, then that seems like a win, yes?

**Comment by richelbilderbeek** [comment]
Hi @sckott, thanks for your thoughts! 

I fully agree that -in hindsight- I maybe should have used the program by @dansondergaard (yes, I think it's awesome!).

On the other hand, to throw useful (Linux-only) code away just for a potential superior alternative, seems like unpragmatic. Apparently, [ropensci editors are working on accepting bindings to single-OS tools](https://github.com/ropensci/dev_guide/pull/118).

I think binding to a single-OS tool encourages the authors of that tool to broaden their range of OSes. 

And back to your point, I think that a package that binds to @dansondergaard's version will be superior and I will happily redirect my users to such a superior package. Or perhaps transition to using it, without hurting my users.

I think the only/biggest showstopper would be the authors of the TMHMM tool I call from R. If they don't want to, I will happily go the extra mile to use @dansondergaards work.

**Comment by sckott** [comment]
Thanks for the reply and explanation. Sounds like we should wait to see what TMHMM person says.

**Comment by noamross** [comment]
Let me just comment here on how this package fits into overall scope given the proposed new scope definition at https://github.com/ropensci/dev_guide/pull/118

-   Yup, is a scientific and not a general system utility
-   This is a very thin wrapper - calling the program via `system` and returning the results as a string.  There's not any particular data handling/parsing (not that there _needs_ to be)
-   This package partially handles installation.  However, it mostly handles it in terms of putting the install directory in a place easy for the package to handle (In an `rappdirs` directory).  There's not a complex installation process to overcome for this utility - the biggest hurdle, still present when using the R package, is requesting permission to use it.
-   The utility is not open sourced or open licensed, but an alternative open-source version exists.
-   The package only works on a single platform, because the utility is single platform.  The alternative is multi-platform, or this package could attempt to make the utility multi-platform via a Docker/[**stevedore**](https://github.com/richfitz/stevedore) based solution.

Based on the above, I think that on balance, this package doesn't meet our criteria.  It doesn't add significant value over a user handling the system utility themselves, and we can see clear cases - using the alternative utility or another multi-platform, where a different package would supplant this one.

Thoughts @richelbilderbeek or @sckott?

**Comment by richelbilderbeek** [comment]
Thanks @noamross for the crisp overview over the decision making. I can fully understand would the submission not fulfil the criteria.

But I wonder, regardless of these points, it would save people time (especially beginner R users) to re-invent the wheel. The package does what it is made for well. If the goal of rOpenSci is to help people be more efficient with their time, then a pragmatic acceptance of this package maybe would be the lesser evil. As a use case: I already depend on this package ([the epitopeome package](https://github.com/richelbilderbeek/epitopeome)).

On the other hand, @sckott already gave a superior solution and I feel a rejection would be justified. It would give a clear signal to the TMHMM authors to support more platforms. Sure, I'll have to write a new package, but well, sometimes that's what it is :rainbow:

**Comment by richelbilderbeek** [comment]
Got this in return:

> All the CBS packages work in the same way, so we would kindly ask you to follow the model we have. 
> Hope that can be incorporated in the process of setting it up. 

I suggest I retract this submission and use the TMHMM implementation suggested by @sckott.

Agree?

**Comment by sckott** [comment]
What is "the model we have" exactly?

**Comment by richelbilderbeek** [comment]
This one: [https://github.com/dansondergaard/tmhmm.py](https://github.com/dansondergaard/tmhmm.py)

**Comment by dansondergaard** [comment]
@richelbilderbeek, I believe @sckott referred to the model used for the CBS software, not what the alternative is :)

**Comment by sckott** [comment]
Agree, makes sense to use https://github.com/dansondergaard/tmhmm.py

**Comment by richelbilderbeek** [comment]
I suggest to close this Issue, I will create a new one if I submit a package that is FOSS.
