### ISSUE TITLE
Submission: bwimage

### ISSUE THREAD

**Issue by biagolini** [ropensci/software-review#319]
Submitting Author: Carlos Biagolini-Jr (@biagolini)  
Repository: https://github.com/biagolini/bwimage
Version submitted:   1.0
Editor: TBD  
Reviewer 1: TBD  
Reviewer 2: TBD  
Archive: TBD  
Version accepted: TBD   

---

Package: bwimage
Type: Package
Title: Describe Image Patterns in Natural Structures
Version: 1.0
Date: 2019-06-24
Author: Carlos Biagolini-Jr.
Maintainer: Carlos Biagolini-Jr.<c.biagolini@gmail.com>
Description: A computational tool to describe patterns in black and white images from natural structures. 'bwimage' implemented functions for exceptionally broad subject. For instance, 'bwimage' provide examples that range from calculation of canopy openness, description of patterns in vertical vegetation structure, to patterns in bird nest structure.   
License: GPL (>= 2)
URL: https://github.com/biagolini/bwimage
VignetteBuilder: knitr
Encoding: UTF-8
RoxygenNote: 6.1.1
Imports:
    jpeg, 
    png 
Depends: 
    stats, 
    utils
Suggests: 
    knitr,
    rmarkdown,
    covr

```

```

## Scope 

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [X] data extraction
	- [ ] database access
	- [ ] data munging
	- [ ] data deposition
	- [ ] reproducibility
	- [ ] geospatial data
	- [ ] text analysis
	

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
This is a Software Tool Article, which proposes a tool to describe patterns from black and white images.

-   Who is the target audience and what are scientific applications of this package?  
The application of this method is exceptionally broad, as it can be applied in any project that uses black and white image analyses, across a wide range of taxa, including plants and animals. 

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
As far as I know, no other R package had this methodological scope to image analyses. 

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.  This package:

- [ X] does not violate the Terms of Service of any service it interacts with. 
- [ X] has a CRAN and OSI accepted license.
- [ X] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme). 
- [ X] includes [documentation with examples for all functions](https://ropensci.github.io/dev_guide/building.html#documentation).
- [X ] contains a vignette with examples of its essential functions and uses.
- [ X] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [ X] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [X ] Do you intend for this package to go on CRAN?  
- [ ] Do you wish to automatically submit to the [Journal of Open Source Software](http://joss.theoj.org/)? If so:

<details>
 <summary>JOSS Options</summary>  

  - [ ] The package has an **obvious research application** according to [JOSS's definition](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements).
    - [ ] The package contains a `paper.md` matching [JOSS's requirements](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) with a high-level description in the package root or in `inst/`.
    - [ ] The package is deposited in a long-term repository with the DOI: 
    - (*Do not submit your package separately to JOSS*)  
  
</details>

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:  

<details>
<summary>MEE Options</summary>  

- [ ] The package is novel and will be of interest to the broad readership of the journal. 
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [X ] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by annakrystalli** [comment]
Hello @biagolini and apologies for the late reply.

In general, the package feels likely to be in scope. However:

The first major issue that was also mentioned in the pre-submission enquire for `GenTag` is that there are no tests. We require at least 75% test coverage for the package

Another issue I can see is that while the package is described as a general package for _"analyzing patterns in black and white images from natural structures"_  it actually feels geared towards vegetation image analysis, with many function names indicating a very specific use/method.  

The fact that there is no [`pkgdown`](https://pkgdown.r-lib.org/articles/pkgdown.html) documentation, a very minimal vignette (the README) and all functions are in a single R script makes it really hard to scan through the functionality provided and get a better feel for the package. 

This isn't necessarily an issue but might need clearer definition within the documentation. Otehrwise some examples of broader use might be required.

**Comment by biagolini** [comment]
Thank you @annakrystalli for your answer. In the following topics I address your questions:

- Coverage test is about 80% for bwimage: https://codecov.io/gh/biagolini/bwimage
- pkgdown documentation was added
- Functions were split in three R scripts cording to each type of application
- Can you be more specific in which part of documentation I must be more clear?

**Comment by annakrystalli** [comment]
Hi @biagolini and thanks for your response and for the improvements made already.  It helped get a better understanding of the package. However, on closer inspection, it appears that it is more of an analysis package. Currently, rOpenSci are not able to provide review for such packages, although it is [an area we are actively working on](https://ropensci.org/blog/2019/07/15/expanding-software-review/), so perhaps trying again in future. 

I'll also respond to your specific points to help clarify what I meant, hopefully it will be useful for improving the package even more:

<br>

***

> * Coverage test is about 80% for bwimage: https://codecov.io/gh/biagolini/bwimage

This is true, but it is because argument `type` has been set to `"all"` in the call to `codecov` in `.travis.yml`. This considers roxygen examples and demonstration of functions in vignettes as coverage. 

```r
> covr::package_coverage(type = "all")
#> bwimage Coverage: 80.41%
#> R/IntFunctions.R: 71.51%
#> R/cnvIM.R: 81.94%
#> R/ImageAnalysis.R: 91.42%
```

What we are interested in is the **coverage of the tests** which you get with `type="tests"` or without specifying type (the default). In the case of your package it is 0%
```r
covr::package_coverage()
#> bwimage Coverage: 0.00%
#> R/cnvIM.R: 0.00%
#> R/ImageAnalysis.R: 0.00%
#> R/IntFunctions.R: 0.00%
```
Indeed checking the single `tests/testthat/test-bwimage.R` file, the only test in there is the example test included  when you use `usethis::use_test()` to create the test file:
```r
test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})
```
This **needs to be populated with tests testing the behaviour of your functions**. Only then will the test coverage of the package increase. Have a look at this [testing](http://r-pkgs.had.co.nz/tests.html) chapter for more info.

I also see that you have included your authorisation token in your `.travis.yml`. This is not necessary as travis handles authorisation (see package [`covr` documentation for more details](https://covr.r-lib.org/)) but more importantly something you should avoid for security reasons. In general, I would recommend you [do not commit and push authorisation tokens to GitHub](https://dzone.com/articles/security-best-practices-for-managing-api-access-to). I recommend you remove this one from the file, revoke it and create a new one so that this one can no longer be used by anyone pretending to be you.
<br>

***
> * pkgdown documentation was added
> * Functions were split in three R scripts cording to each type of application

Great! However, I am unable to view it at default the url which should be `https://biagolini.github.io/bwimage/`. I'm not sure whether [GitHub pages has been enabled](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages) and the source also needs to be set to **master branch /docs folder** 

Once that's done, I would suggest you enter a description and the url to the online documentation here:
![image](https://user-images.githubusercontent.com/5583057/61362728-958c7f00-a87a-11e9-944f-58dacdc8342d.png)
<br>
***
> * Can you be more specific in which part of documentation I must be more clear?

What I meant is that the functionality of the package seems more specific (ie in my view it helps with the analysis of vegetation structures, indeed the `denseness` functions reference a paper concerned with exactly that: _Multiparameter analysis of vertical vegetation structure based on digital image processing_ ) while the description of 
> A computational tool to describe patterns from black and white images.
 seems too general. The key for good documentation, and the initial descritpion especially, is for the users for which the package is useful and equally for those for who it is not, to be able to figure that out very quickly.

Hope this helps!
