### ISSUE TITLE
rdbhapi : R package to simplify API access to data on higher education in Norway

### ISSUE THREAD

**Issue by makinin** [ropensci/software-review#443]
Submitting Author Name: Marija Ninic
Submitting Author Github Handle: @makinin
Other Package Authors Github handles: (comma separated, delete if none) @sigve-berge-hofland
Repository:   https://github.com/makinin/rdbhapi
Version submitted: 2.1.0
Submission type: Standard
Editor: @haozhu233
Reviewers:  TBD 

Language: en
Archive: TBD
Version accepted: TBD

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: rdbhapi
Title: Interface to 'DBH-API' 
Version: 2.1.0
Authors@R: c(person(given = "Marija",family = "Ninic",role = c("cre", "aut"),email = "marija.ninic@nsd.no", comment=c(ORCID ="0000-0001-8484-5817")),person(given=c("Sigve", "Hofland"), family="Berge", role = "aut"))
Description: Downloads 'DBH-API'<https://dbh.nsd.uib.no/tjenester.action> data as dataframes. These data are in machine-readable format and provides information about education, finances, research and publications. 
License: MIT + file LICENSE
Encoding: UTF-8
RoxygenNote: 7.1.1
Imports: 
    httr,
    readr,
    rjson,
    jsonlite,
    rlang,
    stats
Suggests:
    spelling, 
    knitr,
    rmarkdown,
    testthat
VignetteBuilder: knitr
Language: en-US

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ x] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences): his package falls under the category of data retrieval because it simplify API access from to data on higher education in Norway, as provided by NSD - Norwegian Centre for Research Data. This package read data from API into R dataframe.

-   Who is the target audience and what are scientific applications of this package? Students of social sciences and researches who work with data about higher education in Norway.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)? No, there is not

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)? Yes it does

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @maelle the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.

- [ x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [ x] does not violate the Terms of Service of any service it interacts with.
- [x ] has a CRAN and OSI accepted license.
- [ x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x ] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [ x] contains a vignette with examples of its essential functions and uses.
- [ x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [ x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [ x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ x] The package is novel and will be of interest to the broad readership of the journal.
- [ x] The manuscript describing the package is no longer than 3000 words.
- [ x] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [ x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by noamross** [comment]
@ropensci-review-bot assign @haozhu233 as editor

**Comment by haozhu233** [comment]
### Editor checks:

- [X] **Documentation**: The package has sufficient documentation available online (README, pkgdown docs) to allow for an assessment of functionality and scope without installing the package.
- [X] **Fit**: The package meets criteria for [fit](https://devguide.ropensci.org/policies.html#package-categories) and [overlap](https://devguide.ropensci.org/policies.html#overlap)
- [X] **Automated tests:** Package has a testing suite and is tested via a CI service.
- [X] **License:** The package has a CRAN or OSI accepted license
- [X] **Repository:** The repository link resolves correctly

---

#### Editor comments

Hi @makinin, I'm your guest editor for the rdbhapi submission. I'm very sorry for the delay! I got dragged by many other things in my life. I'll help you move forward with the reviewing process as fast as I can. 

I took a look at the package and I like its overall quality so far. I think the topic of this package is a good fit for ropensci and the existence of this package does make utilizing the DBH-API a lot easier (especially when I can't fully understand the Norwegian API documentation 😂). In terms of coding, I especially like how you use R's environment to host all the "private fields" of the API class if there is one. There are some small issues I found. If you can address them while I found reviewers for you, it would be great and it would also help the reviewers finish their reviewing process. 

- It seems that this package is not on CRAN yet. The installation instruction in README is a little misleading. 
- You do have a pkgdown website hosted at [https://makinin.github.io/rdbhapi/](https://makinin.github.io/rdbhapi/). Could you post this link in the link field of the github repository description? It will make it easier for people to find that site. 
- After I run `goodpractice::gp()`, I got quite a few comments on code coverage and long code lines. If you can address them that will be great!
- There is a codecov setup for this repository. However, it seems that it has not been updated since 2 years ago. Is it possible for you to relink the code coverage check and the repository and update the code coverage number?

I will start to search for reviewers and I will keep you posted. 

---

Reviewers:
Due date:

**Comment by makinin** [comment]
@haozhu233 
Hello and thank you for your suggestions. 
I have fixed long code lines and run checks after that but I get the following error message Project file "rdbhapi.Rproj" is not a valid MSBuild project file which must be an XML in appveyor and do not know how to fix it. I have run codecov again but since it was a lot of chaneges since first version for two years ago I have to write new examples.
Best regards,
Marija

**Comment by haozhu233** [comment]
No problem @makinin take your time! :) 

For the appveyor issue, have you tried out https://github.com/krlmlr/r-appveyor? That might be helpful in this case.

**Comment by haozhu233** [comment]
Hi @makinin, how's going with the rdbhapi package? Have you finished this round of updates? Feel free to let me know if I can provide any help or assistance. :)

**Comment by makinin** [comment]
Hi @haozhu233 , I followed your suggestions and I updated package. However although I add examples codecov return coverage 0 %  
Best regards,
Marija

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot check package

**Comment by mpadge** [comment]
Sorry @ldecicco-USGS, the submission templates have changed somewhat since that submission. I've edited to new expected form, so should be okay to try again.

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot check package

**Comment by haozhu233** [comment]
@makinin Hi Marija, sorry for the long delay. For some reason I didn't see your reply. 

In terms of the coverage issue, I noticed that the codecov.yml was changed since the last working check. Can you try to put back this removed line and see how it goes?

https://github.com/makinin/rdbhapi/blob/4dfe1f52b26c69c381b851df9290d8afb990a84c/codecov.yml#L14

**Comment by emilyriederer** [comment]
Hi @makinin  ! We are doing a sweep of stale review issues. Since this review has been open and inactive for so long, much may have changed including author, editor, and reviewer bandwidth and ever-evolving rOpenSci best practices. As such, I'm closing this issue. If you still have interest and capacity, we would welcome you to open a new submission issue!
