### ISSUE TITLE
octolog

### ISSUE THREAD

**Issue by assignUser** [ropensci/software-review#502]
**Reviewers:** 

Submitting Author Name: Jacob Wujciak-Jens
Submitting Author Github Handle: @assignUser
Repository:  https://github.com/assignUser/octolog/
Version submitted: 
Submission type: Standard
Editor: @annakrystalli
Reviewers: @pat-s, @annakrystalli
Due date for @pat-s: 2022-03-30
Due date for @annakrystalli: 2022-06-07
Archive: TBD
Version accepted: TBD
Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: octolog
Title: Better 'Github Action' Logging
Version: 0.1.1.9000
Authors@R: 
    person("Jacob", "Wujciak-Jens", , "jacob@wujciak.de", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0002-7281-3989"))
Description: Provides an API for 'Github' <https://github.com> workflow
    commands and makes it possible to signal conditions from within R that
    will create annotations when used within 'Github Actions'
    <https://github.com/features/actions> but raise normal R conditions
    when used interactively.
License: MIT + file LICENSE
URL: https://github.com/assignUser/octolog,
    https://assignuser.github.io/octolog/
BugReports: https://github.com/assignUser/octolog/issues
Imports: 
    cli (>= 3.0.0),
    fs,
    glue,
    magrittr,
    openssl,
    rlang (>= 1.0.0),
    utils,
    withr
Suggests: 
    knitr,
    covr,
    mockery (>= 0.4.2.9000),
    testthat (>= 3.0.0),
    rmarkdown
Remotes: 
    r-lib/mockery
Config/testthat/edition: 3
Config/testthat/parallel: true
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.2
VignetteBuilder: knitr

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
Octolog aims to make it easier for R author's to use the full power of Github Actions as a CI service.

-   Who is the target audience and what are scientific applications of this package?
Using CI is recognized as an important part in the development process of (scientific) R software and octlog aims to make this easier and more powerful.  
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

As far as I know there are none.
-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.
https://github.com/ropensci/software-review/issues/501
-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by jooolia** [comment]
@ropensci-review-bot assign @annakrystalli  as editor

**Comment by jooolia** [comment]
@ropensci-review-bot assign @annakrystalli as editor

**Comment by assignUser** [comment]
Thank you @jooolia for your work so far! 

I just wanted to note that my test coverage as displayed by {pkgcheck} has seemingly dropped below 75% but this is due to an issue with {covr} and the way it handles `expect_snapshot` tests: https://github.com/r-lib/covr/issues/482
The actual coverage is >90%: https://app.codecov.io/gh/assignUser/octolog

**Comment by annakrystalli** [comment]
Hello @assignUser and many thanks for your package submission! 👋

I'll be your editor and will start editor checks shortly and report back. 👍

**Comment by assignUser** [comment]
Hey @annakrystalli do you need any input from my side at this point to continue the submission?

**Comment by annakrystalli** [comment]
@ropensci-review-bot assign @pat-s as reviewer

**Comment by annakrystalli** [comment]
Sounds good to me.

**Comment by pat-s** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

-   **Briefly describe any working relationship you have (had) with the package authors.**
-   [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor *before* starting your review).

#### Documentation

The package includes all the following forms of documentation:

-   [x] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
-   [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
-   [x] **Vignette(s):** demonstrating major functionality that runs successfully locally
-   [x] **Function Documentation:** for all exported functions
-   [ ] **Examples:** (that run successfully locally) for all exported functions
-   [x] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

-   [x] **Installation:** Installation succeeds as documented.
-   [ ] **Functionality:** Any functional claims of the software been confirmed.
-   [x] **Performance:** Any performance claims of the software been confirmed.
-   [x] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
-   [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 2,5

-   [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

------------------------------------------------------------------------

### Review Comments

## General

Overall I think the package is a useful contribution and can be of good use use in CI/CD workflows. It simplifies the combined usage of local and CI/CD execution. I will also try it out in combination with {tic} to better highlight and format log outputs! In fact, I've played around with it a bit in the `octolog` branch in {tic} (see [CI runs](https://github.com/ropensci/tic/actions)) and the condition signaling worked as expected!

Please finde some comments below of points which could possibly be improved/changed to make the package even better :)

I think the motivation and intro could profit from one or two sentences more highlighting the scope of the package and how {octolog} might improve the experience of a package author/analyst who works with GHA. I think the word "additionally" suggests that the condition signaling in R is just a "nice side effect" whereas it is actually one of the main points. To be clear: I think this sentence just needs a slight rewrite and the word "additionally" should probably be avoided to not "value down" this part.

I was wondering where the name {octolog} originates from? I couldn't find a statement about it - maybe this could be added? (I assume it originates from the "octo" being GH logo animal - but maybe I am wrong? :)

## Dependencies

I know this usually is a hot debate with many different views but let me share mine :) I see that there is a strong focus on tidyverse packages (which is not a problem per se and tidyverse packages are of course well programmed packages), yet they usually bring in additional dependencies and one has to ask themselves if it's worth it - especially on the R package side (scripting/data analysis is a different use case).
Please don't see this is a "blocker" or similar, just as a personal opinion or "food for thought" :)

I think the package could be substantially reduced WRT to package dependencies:

-   Often the magrittr pipe is only used in scripting/analysis and not within packages as it can be easily replaced

-   {rlang} is similar to {magrittr} state above, though I see that it might do some things "better" than base R checks etc. I see that mainly `rlang::trace_back()` is used and one call to `rlang::exec()`. I haven't yet made use of the former but wanted to ask which additional benefits the use of `rlang::trace_back()` brings compared to `traceback()` WRT to the package functionality?

-   I like to use {fs} in scripting but try to avoid in packages due to it's dependency on libuv. This is especially costly and (possibly annoying for unexperienced users) in CI as the system dependency first needs to be installed. This costs time during every run and I think the {fs} dependency could be easily avoided.

Avoiding all of the above would leave the package with {cli}, {glue} and {withr} as direct dependencies (in IMPORTS) which would be an improvement to me.

## README

-   The initial example and screenshot is somewhat hard to understand for first time users. To make it fully clear I'd suggest to also add an example how the error msg would look like in an interactive example - maybe even side by side in a a table?

-   Installation: Given that {pak} is still quite unstable and non-standard WRT to package installation (and is a third-party package), I'd not use it as the "default" installation method. I'd suggest to use `install.packages()` and mention {pak} as an alternative. In addition, `remotes::` should be used instead of `devtools::`

-   The following URL in the README leads to a 404: [website](https://github.com/assignUser/octolog/blob/main/assignUser.github.io/octolog)

-   Footnote 2 states that GHA is "only free for public repos". It is also free for private repos but with a limited amount of usage (in mins)

## Vignettes

## Get Started

-   The vignette indicates that {octolog} only works with {cli} message output and not with normal `message()` or `warning()` calls. If so, this should be highlighted more prominently at the start of the vignette or in the README

-   The example on `octo_abort()` should maybe get it's own section. Especially because "This can be useful if you want a workflow to fail (e.g. to block a PR) by throwing an error but do not want to stop the R process." is one of the selling features of {octolog}

-   The "masking" section could profit from an additional R code block showcasing the R code directly as the screenshot is somewhat hard to read. Also it might be of interested to note why these two functions differ and which one should be used in which scenario.

-   The "stopping command parsing" section could profit from a toy example. I find it quite hard to image a scenario in which the describe command could be of good use. The last two sentences "This is not intended to protect against other R code. Due to R's metaprogramming capabilities it is not possible to protect the token within the same R session." are not fully clear to me in this context. I think this section could profit from more context and a clear example :)

## Functions

-   <https://jacob.wujciak.de/octolog/reference/enable_github_colors.html> : Examples throw an error

-   Maybe group the pkgdown reference output in meaningful categories?

-   `octo_add_path()` : the description is unclear to me

-   `octo_mask_value()`: examples error

-   `octo_start_group()`: The example errors. I think this could be worth getting it's own section in a vignette?

-   `octocat()`: what is it's relation to the other cli-based functions?

## Stylistic

-   Github -\> GitHub

-   It would be great to somehow differentiate the package from normal text, either by formatting is as code or wrapping it in brackets such as {octolog}

-   Typos:

    -   README: powerful,free (whitespace)

    -   Get started vignette: using `octo_stop_commands`.Internally the function

-   Screenshots: Could possibly be of higher quality

**Comment by annakrystalli** [comment]
Thanks @pat-s for your review! @assignUser I'm still looking for a second reviewer so I suggest holding out responding or making changes (at least not in the `main` branch) until both reviews are complete.

**Comment by Athene-ai** [comment]
Hi @annakrystalli ! I would like to review this package

**Comment by annakrystalli** [comment]
Dear @assignUser, Many apologies for the delay in the review. I've had a lot of trouble finding a second reviewer (and in between have also moved countries!). I'm settled now though so to get things moving again and given I have no conflict of interest with the package, I'll go ahead an volunteer as a reviewer. ☺️

**Comment by annakrystalli** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions
- [x] **Examples:** (that run successfully locally) for all exported functions
- [x] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [x] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 4

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

Fistly many apologies for the delays in getting the package through the review process. As for the package, given how popular GitHub Actions are becoming (and it's great to hear it works nicely for `tic` too), it's a nice and clean addition to packages in the R continuous integration space.

Thank you as well again @pat-s for your excellent review. I pretty much agree with all of @pat-s's comments, especially the one on streamlining dependencies. I think the suggestion is a smart one and second it. 

So as not to repeat the same points, I focus on a few additional comments I have, primarily building on my initial points in the editor's checks as well as some mentioned by @pat-s regarding documentation.



#### Documentation:

##### Minor points 

- In the pgkdown docs, there are many errors in examples of functions with the error `could not find function <function_name>`)  e.g.  `enable_github_colors`, `encode_string`, `octo_warn` and more (some of which run locally).

- When running examples locally, often `Sys.setenv(GITHUB_ACTIONS = "true")`
needed to be run. It would be good if example code cleaned up after itself with `withr::local_envvar(GITHUB_ACTIONS = "true")` like you do in tests.

##### General package documentation

While I appreciate that you point to a live example of GA runs using octolog from the README / Getting started, I feel more explanation of what is going on would be appreciated by new users.

For example, for starters, I would explicitly link to the [`test-octolog.yaml`](https://github.com/assignUser/octolog/blob/main/.github/workflows/test-octolog.yaml#L34-L89) workflow that is being run.

Then I would point the user to the lines in the workflow that are running the R code that are generating the messages by focusing on this section and explaining what is going on:
https://github.com/assignUser/octolog/blob/8e71de9077f0f6a3e5fbefb78be5c6f32c0cbf47/.github/workflows/test-octolog.yaml#L34-L89

More specifically I might explain that it's sourcing [`/.github/workflows/R/conditions.R`](https://github.com/assignUser/octolog/blob/main/.github/workflows/R/conditions.R) (which is so short I might even include it in the docs) and then running R code from the workflow yaml itself.

For me the key is to make clear not just the code that generates the output in GA, but also where they appear in R code in the repo and how they then get run through GitHub Actions

Two additional suggestions to make the usefulness of the package to the R user more concrete and easy to experiment with. 

1. While your examples in `test-octolog.yaml` are comprehensive with respect to the generic types of outputs the octolog API and your package offer, I feel they could be improved in terms of helping R users visualise why it would be useful to include them. It would be good to provide some more real life examples (especially more realistic R continuous integration scenarios) and explain some of the ways in which R code might be run in GA (e.g. raw R code in the workflow yaml, sourcing R code, code being run as part of package tests, package loading). 

  Perhaps you could set up a tiny R package and placing octolog code in actual function files in R. Messages could be deliberate error messages, package loading messages, package dependency checks, progress messages, basically whatever you think you might inspire users to visualise their use.

  I don't want to be prescriptive here, I'm just trying to motivate some ideas. The important point of all of this is to give a better and broader view of how they might be useful in GitHub Actions to an R user.

2. If you set up such a demo repository, you could even set it up as a template that users could copy (or if not just fork) and direct them to use it as a playground for testing out package functionality. This could get them started much quicker with experimenting with package functionality and for me greatly improve understanding of how the package works and how they might use it.


#### Minor points

##### good practice notes

There are still a couple of suggestions being picked up by `goodpractice::gp()`. I feel the ones about line length are not a huge deal but they still remain best practice for readability. 

The note about using `setwd()`, again, I'm not sure it's a big deal because it's being used in tests and it seems and you clean up nicely with `withr::defer(setwd(old_wd))`. I'm guessing this is the best way to achieve what you're trying to do. If there's no other way, I think this will be fine.

#### spell check

Probably the only potentially valid typo is in the roxygen docs for `enable_github_colors`:
```
sideeffects         enable_github_colors.Rd:29
```

#### Conclusion

I know it might feel like my suggestions are overboard but I feel it's really important to consider the perspective of complete beginners, walk them through very explicitly how things work (instead of linking to examples with quite a few working parts that they need to reverse engineer) and help them visualise how the package can help them.

Very open to hearing your thoughts on this!

**Comment by annakrystalli** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/502#issuecomment-1067080447 time 2.5

**Comment by annakrystalli** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/502#issuecomment-1149620624 time 4

**Comment by assignUser** [comment]
Thanks again to both of your for the informative reviews! It has been sometime but I managed to carve out some time to work on {octolog}. On that topic, @annakrystalli is there a deadline for me?

@pat-s I have removed {fs} and {magrittr}. {rlang} has to stay as it is a (hidden) dependency for [`cli_abort`](https://github.com/r-lib/cli/blob/main/R/rlang.R#L43) etc..
This also means that my actual dependencies are {cli} and {withr} with {glue} and {rlang} being "free" via {cli}. With these dependencies being very lightweight, without system dependencies and made for use in packages I don't think it is worth it to remove anymore dependencies (which would basically mean re-writing in base R 🙀 ). 

While I am not entirely sure that {fs} is really such an issue (the compilation takes < 30s / use rspm & cache in CI!) it did not require big changes. {magrittr} on the other hand was completely superfluous and just added because I like how the code looks using it 😁.

@annakrystalli I removed most of the {lintr} issues but have too keep some of the line length ones as those are links and I have not found a way to add a line break [without breaking](https://github.com/assignUser/octolog/runs/7055289264?check_suite_focus=true#step:6:88) the link.

With the "technical" issues addressed I will work on improving the documentation next!

**Comment by annakrystalli** [comment]
Nice work @assignUser! While we suggest a response within a couple of weeks of reviews being submitted, there isn't a hard deadline really to when all comments must be resolved. The work required to resolve comments varies from package to package and we all understand having to carve out time can be hard especially during summer holiday time! So don't worry too much about a given deadline. Look forward to seeing the documentation! 😃

**Comment by pat-s** [comment]
> While I am not entirely sure that {fs} is really such an issue (the compilation takes < 30s / use rspm & cache in CI!) it did not require big changes. {magrittr} on the other hand was completely superfluous and just added because I like how the code looks using it 😁.

I also like to use both in scripting, though pkg dev is usually a different field. It's also not only about installation time/effort on CI but also on various systems (a system dep can be a blocker for some people in some restricted environments as they cannot install anything themselves - as a system engineer/admin I face this situation quite often). This reasoning does not really apply for your package as it is aimed at CI in the first place, but I'd would just call it "good practice" to think about these things and try to avoid such "convenience" packages in pkg dev if there are (robust) base R solutions - especially if the transition is cheap. Sometimes there are not or very complicated workarounds only, so it always differs...

(sorry for the wall of text, just some personal thoughts, it's ofc up to you what you do WRT to deps in the end :) )

**Comment by maurolepore** [comment]
Dear @assignUser, my EiC rotation just started and I'm checking the status of every open issue. Any updates?

**Comment by assignUser** [comment]
@maurolepore Hey! Sorry for the long silence, there are no updates but I will try to move this for ward soon(tm)! Thank you for checking in.

**Comment by annakrystalli** [comment]
Hello @assignUser ! Was wondering whether you had any updates on progress on the package? Do you feel we should put the review on hold?

**Comment by assignUser** [comment]
Hey, sorry. I have done some work on this but github has changed the API in parts for security reason and I have to adapt to this (though it should not be to hard) I will update you in a bit (~2 weeks ok?)

**Comment by jhollist** [comment]
@assignUser I am currently serving as the EIC and wanted to check in on this submission.  Have you had a chance to update the package?

**Comment by assignUser** [comment]
I really hoped I would have more time to get this up to speed but at the moment that just hasn't worked out. I do appreciate the work everyone has put in so far, of course especially @pat-s and @annakrystalli as reviewers. You suggestions are very good and gave a good perspective and I hope to implement them at some point.

With my time constriants even if the package get's accepted it would be defacto abandond from the get go and I don't think that's the purpose of this process. For that reason I am going to clsoe this. 

Thank you again everyone ❤️
