### ISSUE TITLE
CRediTas: a tiny package to generate CRediT authors statements

### ISSUE THREAD

**Issue by jospueyo** [ropensci/software-review#576]
**Date accepted:** 2023-04-11

Submitting Author Name: Josep Pueyo-Ros
Submitting Author Github Handle: @jospueyo
Repository:  https://github.com/jospueyo/CRediTas
Version submitted: 0.1.0
Submission type: Standard
Editor: @emilyriederer
Reviewers: @zambujo, @msperlin
Due date for @zambujo: 2023-04-04
Due date for @msperlin: 2023-04-06
Archive: TBD
Version accepted: TBD
Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: CRediTas
Type: Package
Title: Generate CRediT Author Statements
Version: 0.1.0
Authors@R: 
    c(
      person(given = "Josep", family = "Pueyo-Ros", email = "josep.pueyo@udg.edu", 
      role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1236-5651")))
Description: CRediTas is a tiny package to generate CRediT author statements (https://credit.niso.org/). 
    It provides three functions: create a template, read it back and generate the CRediT author statement in a text file.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
URL: https://github.com/jospueyo/creditas
BugReports: https://github.com/jospueyo/creditas/issues
RoxygenNote: 7.2.1
Suggests: 
    testthat (>= 3.0.0)
Config/testthat/edition: 3
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [x] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

The package facilitates the creation of CRediT author statements, which are mandatory for many journals and encourage good practices in coauthoring scientific publications.

-   Who is the target audience and what are scientific applications of this package?

The target audience are authors of scientific publications. There are not scientific applications of this package. It helps in the good practices of open science.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

There are not as far as I know

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

Long lines in test-write_cras.R because I compare a string with a generated text file. If I break the lines I cannot compare both.
Avoid T and F in write_cras.R: I do not use T or F, in line 1, there is "CRediT" which confounds the algorithm.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by jospueyo** [comment]
All items marked with ✖️ have been resolved.

**Comment by jospueyo** [comment]
@ropensci-review-bot check package

**Comment by jospueyo** [comment]
@ropensci-review-bot check package (I added some sanity checks to a function)

**Comment by jospueyo** [comment]
@ropensci-review-bot check package

**Comment by maurolepore** [comment]
@jospueyo thanks a lot for your submission!

I'm discussing the scope with the editors board. 

To increase the chance they will see the merit of {credit} you might want to unpack in README why the task this package solves is a tedious one. README says it's tedious but it's not immediately obvious how.

**Comment by jospueyo** [comment]
I just pushed this explanation.

**Comment by maurolepore** [comment]
@jospueyo 

Thanks for the explanation and for your patience. 

I discussed with other editors and find this package to be in scope. I'll start looking for a handling editor.

**Comment by maurolepore** [comment]
@ropensci-review-bot assign @emilyriederer as editor

**Comment by emilyriederer** [comment]
Hi @jospueyo ! I'm delighted to be handling this from the editorial side. I'm traveling for work W-F so I may be a bit slower to respond, but I thought I'd share some initial feedback to get us started. Thanks again and I look forward to working together.


### Editor checks:

- [ ] **Documentation**: The package has sufficient documentation available online (README, pkgdown docs) to allow for an assessment of functionality and scope without installing the package. In particular,
    - [x] Is the case for the package well made?
    - [x] Is the reference index page clear (grouped by topic if necessary)?
    - [ ] Are vignettes readable, sufficiently detailed and not just perfunctory?
- [x] **Fit**: The package meets criteria for [fit](https://devguide.ropensci.org/policies.html#package-categories) and [overlap](https://devguide.ropensci.org/policies.html#overlap).
- [x] **Installation instructions:** Are installation instructions clear enough for human users?
- [x] **Tests**: If the package has some interactivity / HTTP / plot production etc. are the tests using [state-of-the-art tooling](https://devguide.ropensci.org/building.html#testing)?
- [x] **Contributing information**: Is the documentation for contribution clear enough e.g. tokens for tests, playgrounds?
- [ ] **License:** The package has a CRAN or OSI accepted license.
- [x] **Project management**: Are the issue and PR trackers in a good shape, e.g. are there outstanding bugs, is it clear when feature requests are meant to be tackled?
---

#### Editor comments

This is a very clean submission, and it feels close to being ready for reviewers! I notice a few small opportunities before we do the hand-off. 

- Documentation:
  + The documentation is useful but could be improved to help reviewers navigate
  + The vignette could be enhanced to better show different workflows. For example, the text says "The workflow is meant to work with three basic functions. First, we create a template table. It can be created as a `data.frame` and being populated in R. Or as a csv file and being populated in your preferred csv editor.", but the subsequent code chunk does not show all such options/workflows
  + Please consider making a publicly available pkdown site for your docs (instructions [here](https://devguide.ropensci.org/building.html#website))
- License:
  + The package does not appear to use a standard license at the moment. Please refer to [https://devguide.ropensci.org/building.html#licence](this section) of our docs for more options about licenses

---

**Comment by jospueyo** [comment]
- Documentation:
    - I enhanced the vignette by adding different workflows: write a template to a csv file and define custom roles.
    - I created a public pkgdown site at https://jospueyo.github.io/credit/
   
- License:
    - I used the functions `use_mit_license()` from {devtools}. Is this correct?

**Comment by emilyriederer** [comment]
Thanks @jospueyo !  I like the Documentation updates a lot. My mistake on the License -- I somehow saw the `LICENSE` file but missed the `LICENSE.md` file the first time through. I'll start looking for reviewers for this

**Comment by emilyriederer** [comment]
@ropensci-review-bot seeking reviewers

**Comment by emilyriederer** [comment]
@ropensci-review-bot add @zambujo as reviewer

**Comment by emilyriederer** [comment]
Hi @jospueyo - I'm delighted to introduce the first of our two reviewers, @zambujo . I'm still looking for a second reviewer.

**Comment by jospueyo** [comment]
> Hi @jospueyo - I'm delighted to introduce the first of our two reviewers, @zambujo . I'm still looking for a second reviewer.

Hi! Looking forward to hearing your suggestions!

**Comment by emilyriederer** [comment]
@ropensci-review-bot add @msperlin as reviewer

**Comment by emilyriederer** [comment]
Hi @jospueyo - I'm delighted to introduce @msperlin, as seasoned rOpenSci package dev, as your seond reviewer

**Comment by jospueyo** [comment]
> Hi @jospueyo - I'm delighted to introduce @msperlin, as seasoned rOpenSci package dev, as your seond reviewer

Hi! I'm excited about this process! A lot to learn!

**Comment by msperlin** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [X] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [X] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [X] **Function Documentation:** for all exported functions
- [X] **Examples:** (that run successfully locally) for all exported functions
- [X] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [X] **Installation:** Installation succeeds as documented.
- [X] **Functionality:** Any functional claims of the software been confirmed.
- [X] **Performance:** Any performance claims of the software been confirmed.
- [X] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [X] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 1.5

- [X] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

`credit` is a tiny package that automates the process of writing a contribution matrix in the [CRedit](https://credit.niso.org/) format, and can be very useful for academic work, specially in large research groups. 

Overall, I liked the package and it worked fine in my machine. But, in order to improve it, I do have some suggestions:


#### package name

The name `credit` might confuse some users. At face value, an R package named _credit_ is most likely to be related to  mathematical finance and credit markets, and not to the CRedit reference system. My suggestion is to think about  another, more intuitive, name. A couple suggestions: CReditR, contribR,  


#### possible integration with other packages

There are many R packages for [reproducible research](https://cran.r-project.org/web/views/ReproducibleResearch.html), including handling research metadata such as bibtext references. 

I wonder if the authors have checked for any possible integration with these packages. I don't have a direct suggestion, but might be worth the time to check for it.


#### use template for roles

The roles used in the code, as in "Conceptualization", "Methodology" and so on, should be defined in a single place. Do notice that you hard coded (wrote in a script) the roles in function `create_template` and in test `test-read_template`. 

There are many ways to do it, but the simples is just using a function: 

```
get_roles <- function() {

  roles <- c(
  "Conceptualization",
  "Methodology",
  "Software",
  "Validation",
  "Formal analysis",
  "Investigation",
  "Resources",
  "Data curation",
  "Writing - Original Draft",
  "Writing - Review & Editing",
  "Visualization",
  "Supervision",
  "Project administration",
  "Funding acquisition"
)

  return(roles)
}
```

With some simple webscrapping, you could use `testthat` to  check if the template in the package is identical to the template from the [site](https://credit.niso.org/). Whenever the site adds or removes a role, your CHECK process will show it.


#### Function and argument naming

From the ropensci packaging [guideline](https://devguide.ropensci.org/building.html#function-and-argument-naming), I strongly advise to use the object_verb() format (and not the verb_object() pattern) for function names. 


#### use cli messages

Package `cli` is a great way to communicate to the user the output of all functions. It can also include clickable links to local files. This can be very helpful in function `write_cras()`, where the users can simply click in the prompt to open the resulting text file.


#### Functions

##### create_template.R

In the description, you should add a link to the [CRedit](https://credit.niso.org/) and also improve the text. This is your main function, and most likely where users will spend more time. You should try to document it as much as possible.


##### read_template.R

Since this function is reading a template, you should add some test to check if the information in the file has the expected structure (column names, number of columns, ..). If not, issuing a _warning_ might be a good policy, letting the user know that the expected format was not found.


##### write_cras.R

In line 34, I suggest you add an input option for the user to drop (or not) authors without contributions. I suspect that, in large research groups, might be best to also make it explicit that some people did not contribute. 

The description of the function was not found. Since this is a tiny package, I suggest to add a nice and comprehensive description of the function.

**Comment by jospueyo** [comment]
Hi! I opened separate issues in the package repository. Is it fine if I report the changes there? Or should I do here?

**Comment by jospueyo** [comment]
BTW, following the first comment, I changed the package name to CRediTas, and consequently, the repository name. How is this affecting this issue in terms of links or other problems?

**Comment by msperlin** [comment]
> Hi! I opened separate issues in the package repository. Is it fine if I report the changes there? Or should I do here?

I'm fine with the changes as issues. 

> BTW, following the first comment, I changed the package name to CRediTas, and consequently, the repository name. How is this affecting this issue in terms of links or other problems?

I'm not sure of the consequences. Perhaps you should edit the first message. Or, resubmit the package. 
@emilyriederer can you help?

**Comment by emilyriederer** [comment]
Thanks, @jospueyo ! I think if you update the issue title and the link in your first GItHub post, we should be all good

**Comment by jospueyo** [comment]
I addressed all comments of @msperlin. You can see all changes in news: https://github.com/jospueyo/CRediTas/blob/master/NEWS.md

**Comment by msperlin** [comment]
> I addressed all comments of @msperlin. You can see all changes in news: https://github.com/jospueyo/CRediTas/blob/master/NEWS.md

Thanks @jospueyo. Great work. LEt me know if I can help any further.

**Comment by jospueyo** [comment]
## Responses to @zambujo:

- I added both reviewers (do you agree @msperlin?) https://github.com/jospueyo/CRediTas/issues/13
-   I fixed the CSS links in pkgdown https://github.com/jospueyo/CRediTas/issues/7
- I added the description tag to template_create https://github.com/jospueyo/CRediTas/issues/8
- I added the `fix` function in readme and get_started vignette https://github.com/jospueyo/CRediTas/issues/9
- I added related packages to README as suggested https://github.com/jospueyo/CRediTas/issues/10
- I changed `is.null(file)` by `missing(file)` in `cras_write`. https://github.com/jospueyo/CRediTas/issues/11
- I modified `template_create` following your suggestions. I justified why I prefer keeping the i/o functions as part of the package https://github.com/jospueyo/CRediTas/issues/12

**Comment by jospueyo** [comment]
For the long run suggestions, I will keep those in mind. I liked both ideas from @zambujo. The second one is especially interesting for epistemological research. I also have in mind an option to facilitate copy&paste in MS word, currently the **bold** is missed on the way to MS word.

Any contributions will be welcome! ;)

**Comment by msperlin** [comment]
> ## Responses to @zambujo:
> * I added both reviewers (do you agree @msperlin?) [Add reviewers to DESCRIPTION jospueyo/CRediTas#13](https://github.com/jospueyo/CRediTas/issues/13)
> * I fixed the CSS links in pkgdown [fix CSS of pkgdown jospueyo/CRediTas#7](https://github.com/jospueyo/CRediTas/issues/7)
> * I added the description tag to template_create [Add @description to template_create() jospueyo/CRediTas#8](https://github.com/jospueyo/CRediTas/issues/8)
> * I added the `fix` function in readme and get_started vignette [Add fix(cras_table) to readme and get_started jospueyo/CRediTas#9](https://github.com/jospueyo/CRediTas/issues/9)
> * I added related packages to README as suggested [Add realted packages tp README jospueyo/CRediTas#10](https://github.com/jospueyo/CRediTas/issues/10)
> * I changed `is.null(file)` by `missing(file)` in `cras_write`. [Use missing instead of is.null in cras_write() jospueyo/CRediTas#11](https://github.com/jospueyo/CRediTas/issues/11)
> * I modified `template_create` following your suggestions. I justified why I prefer keeping the i/o functions as part of the package [Reduce the scope of template_create() jospueyo/CRediTas#12](https://github.com/jospueyo/CRediTas/issues/12)

I agree.

**Comment by zambujo** [comment]
Many thanks @jospueyo: great to see the changes.

If i/o functionality is to be kept, then I'd like to extend my suggestion of not setting `file = NULL` by default to `template_create()` and `template_read()` (replacing `is.null(file)` with `missing(file)`).

In `template_create()`, I'd also suggest passing file as the second parameter.

And to help beginners, it might be a good idea to include path nomalization with `normalizePath(file)`.

Eg.:

```r
template_create <- function(authors, file, roles = roles_get()) {
  df <- data.frame(Authors = authors)
  mat <- matrix(0, nrow = length(authors), ncol = length(roles))
  colnames(mat) <- roles
  df <- cbind(df, mat)
  if (is.missing(file)) return(df)

  file <- normalizePath(file)
  write.csv2(df, file, row.names = FALSE)
  invisible()
}
```

Last, consider updating the error message [in `cras_write.R`, line 82](https://github.com/jospueyo/CRediTas/blob/4dd185a42e3e0e93cd972ebc01e4b3778bed1b4e/R/cras_write.R#L82). 😉

**Comment by emilyriederer** [comment]
@msperlin - It looks like you're satisfied with the responses to your feedback? If so, can you please document your approval with our {Final Approval Form](https://devguide.ropensci.org/approval2template.html) ?

(Same for @zambujo once you're satisfied with the discussion!)

**Comment by msperlin** [comment]
## Reviewer Response


#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**



Estimated hours spent reviewing: 2

**Comment by jospueyo** [comment]
> Many thanks @jospueyo: great to see the changes.
> 
> If i/o functionality is to be kept, then I'd like to extend my suggestion of not setting `file = NULL` by default to `template_create()` and `template_read()` (replacing `is.null(file)` with `missing(file)`).
> 
> In `template_create()`, I'd also suggest passing file as the second parameter.
> 
> And to help beginners, it might be a good idea to include path nomalization with `normalizePath(file)`.
> 
> Eg.:
> 
> ```r
> template_create <- function(authors, file, roles = roles_get()) {
>   df <- data.frame(Authors = authors)
>   mat <- matrix(0, nrow = length(authors), ncol = length(roles))
>   colnames(mat) <- roles
>   df <- cbind(df, mat)
>   if (is.missing(file)) return(df)
> 
>   file <- normalizePath(file)
>   write.csv2(df, file, row.names = FALSE)
>   invisible()
> }
> ```
>
> Last, consider updating the error message [in `cras_write.R`, line 82](https://github.com/jospueyo/CRediTas/blob/4dd185a42e3e0e93cd972ebc01e4b3778bed1b4e/R/cras_write.R#L82). 😉

Thank you for this final insights!

I followed all your suggestions except using `normalizePath` because then the test failed. Also, I don't fully understand what it does. So, I'd be happy if you could help me in this if you consider important using `normalizePath`.

I also updated the NEWS, that I forgot in the last review.

Best wishes!

**Comment by zambujo** [comment]
## Reviewer Response


#### Final approval (post-review)

- [x] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

Estimated hours spent reviewing: 1

**Comment by emilyriederer** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/576#issuecomment-1494981269 time 5

**Comment by emilyriederer** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/576#issuecomment-1476722900 time 1.5

**Comment by emilyriederer** [comment]
@ropensci-review-bot approve CRediTas

**Comment by jospueyo** [comment]
@ropensci-review-bot finalize transfer of <package-name>

**Comment by jospueyo** [comment]
@ropensci-review-bot finalize transfer of CRediTas

**Comment by yabellini** [comment]
Hi, @jospueyo (rOpenSci Community Manager here). If you want to, I can invite you to our Slack workspace.  I will need your email.  You can send it to yabellini@ropensci.org.
