### ISSUE TITLE
{weatherOz}: an API Client for Australian Weather and Climate Data Resources

### ISSUE THREAD

**Issue by bozaah** [ropensci/software-review#598]
**Date accepted:** 2024-02-09

Submitting Author Name: Rodrigo Pires

Author Github Handle: @bozaah

Other Package Authors Github handles:@adamhsparks, @arhepworth, @jimii19, @syntrix, @becoleary, @HughParsonage, @PaulMelloy, @jonocarroll, @deanmarchiori, @jimjam-slam, @mpadge, @Keith-Pembleton, @maelle

Repository: https://github.com/DPIRD-FSI/weatherOz

Version submitted: v0.0.1

Submission type: Standard

Editor: @ldecicco-USGS

Reviewers: @JanLauGe, @rogerssam

Archive: TBD

Version accepted: TBD

Language: en

------------------------------------------------------------------------

-   Paste the full DESCRIPTION file inside a code block below:

```         
Package: weatherOz
Title: An API Client for Australian Weather and Climate Data Resources
Version: 0.0.1
Authors@R: c(
  person(
    given = "Rodrigo",
    family = "Pires",
    role = c("aut", "cre"),
    email = "rodrigo.pires@dpird.wa.gov.au",
    comment = c(ORCID = "0000-0001-7384-6849")
  ),
  person(
    given = "Anna",
    family = "Hepworth",
    role = "aut",
    email = "anna.hepworth@dpird.wa.gov.au",
    comment = c(ORCID = "0000-0003-0204-6347")
  ),
  person(
    given = "Rebecca",
    family = "O'Leary",
    role = "aut",
    email = "bec.oleary@curtin.edu.au"
  ),
  person(
    given = "Jonathan",
    family = "Carroll",
    role = "aut",
    email = "rpkg@jcarroll.com.au",
    comment = c(ORCID = "0000-0002-1404-5264")
  ),
  person(
    given = "James",
    family = "Goldie",
    role = "aut",
    email = "me@jamesgoldie.dev",
    comment = c(ORCID = "0000-0002-5024-6207")
  ),
  person(
    given = "Dean",
    family = "Marchiori",
    role = "aut",
    email = "deanmarchiori@gmail.com"
  ),
  person(
    given = "Paul",
    family = "Melloy",
    role = "aut",
    email = "paul@melloy.com.au",
    comment = c(ORCID = "0000-0003-4253-7167")
  ),
  person(
    given = "Mark",
    family = "Padgham",
    role = "aut",
    email = "mark.padgham@email.com",
    comment = c(ORCID = "0000-0003-2172-5265")
  ),
  person(
    given = "Hugh",
    family = "Parsonage",
    role = "aut",
    email = "hugh.parsonage@gmail.com",
    comment = c(ORCID = "0000-0003-4055-0835")
  ),
  person(
    given = "Keith",
    family = "Pembleton",
    role = "aut",
    email = "keith.pembleton@usq.edu.au",
    comment = c(ORCID = "0000-0002-1896-4516")
  ),
  person(
    given = "Maëlle",
    family = "Salmon",
    role = "ctb",
    email = "maelle.salmon@yahoo.se",
    comment = c(ORCID = "0000-0002-2815-0399",
                "Contributed to debugging a nasty little bug with CI where
                timezones caused tests to fail due to vcr not recognising the
                URL when run outside of Australia/Perth TZ! Suggested the use of
                `withr::local_timzeone()`, see
                <https://github.com/DPIRD-FSI/weatherOz/commit/b052bf91973b8d7e147a39e8938405a64622634b>.")),
  person(
    given = "Jimmy",
    family = "Ng",
    role = "ctb",
    email = "jimmy.ng@dpird.wa.gov.au"
  ),
  person(
    given = "Steve",
    family = "Collins",
    role = "ctb",
    email = "steve.collins@dpird.wa.gov.au",
    comment = c("Designed weatherOz's hex logo.")
  ),
  person(
    given = "Adam H.",
    family = "Sparks",
    email = "adam.sparks@dpird.wa.gov.au",
    role = "aut",
    comment = c(ORCID = "0000-0002-0061-8359")
  ),
  person(given = "Western Australia Agriculture Authority (WAAA)",
         role = c("cph")))
Description: Provides automated downloading, parsing and formatting of weather
    data for Australia through API endpoints provided by the Department of
    Primary Industries and Regional Development (DPIRD) of Western Australia
    and by the Science and Technology Division of the Queensland Government's
    Department of Environment and Science (DES).  As well as the Bureau of
    Meteorology (BOM) of the Australian government precis and coastal
    forecasts, agriculture bulletin data, and downloading and importing radar
    and satellite imagery files.  DPIRD weather data are accessed through public
    APIs provided by DPIRD, <https://www.agric.wa.gov.au/weather-api-20>,
    providing access to weather station data from DPIRD's weather station
    network.  Australia-wide weather data are based on data from the Australian
    Bureau of Meteorology (BOM) data and accessed through SILO (Scientific
    Information for Land Owners) (Jeffery et al., 2001,
    <doi: 10.1016/S1364-8152(01)00008-1>).  DPIRD data are made available under
    a Creative Commons Attribution 3.0 Licence (CC BY 3.0 AU) license
    <https://creativecommons.org/licenses/by/3.0/au/deed.en>.  SILO data are
    released under a  Creative Commons Attribution 4.0 International licence
    (CC BY 4.0) <https://creativecommons.org/licenses/by/4.0/>.  BOM data are
    (c) Australian Government Bureau of Meteorology and released under a
    Creative Commons (CC) Attribution 3.0 licence or Public Access Licence (PAL)
    as appropriate, see <http://www.bom.gov.au/other/copyright.shtml> for
    further details.
URL: https://github.com/DPIRD-FSI/weatherOz/, https://dpird-fsi.github.io/weatherOz/
BugReports: https://github.com/DPIRD-FSI/weatherOz/issues
License: GPL (>= 3)
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
Imports: 
    apsimx,
    clock,
    crayon,
    crul,
    curl,
    data.table,
    foreign,
    grDevices,
    jsonlite,
    knitr,
    lubridate,
    magick,
    methods,
    readr (>= 1.1.1),
    stringi,
    stars,
    stats,
    terra,
    utils,
    xml2
Suggests:
    covr,
    dplyr,
    ggplot2,
    ggthemes,
    grid,
    gridExtra,
    mapproj,
    maps,
    mailR,
    rmarkdown,
    spelling,
    testthat (>= 3.0.0),
    vcr (>= 0.6.0),
    vdiffr,
    withr
Config/testthat/edition: 3
Depends: 
    R (>= 4.1.0)
X-schema.org-applicationCategory: Tools
X-schema.org-keywords: dpird, bom, meteorological-data, weather-forecast,
    australia, weather, weather-data, meteorology, western-australia,
    australia-bureau-of-meteorology, western-australia-agriculture
X-schema.org-isPartOf: https://www.agric.wa.gov.au/
VignetteBuilder: knitr
Language: en-US
LazyData: true
```

## Scope

-   Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories)
    this package falls under: (Please check an appropriate box below. If
    you are unsure, we suggest you make a pre-submission inquiry.):

    -   [x] data retrieval
    -   [ ] data extraction
    -   [ ] data munging
    -   [ ] data deposition
    -   [ ] data validation and testing
    -   [ ] workflow automation
    -   [ ] version control
    -   [ ] citation management and bibliometrics
    -   [ ] scientific software wrappers
    -   [ ] field and lab reproducibility tools
    -   [ ] database software bindings
    -   [ ] geospatial data
    -   [ ] text analysis

-   Explain how and why the package falls under these categories
    (briefly, 1-2 sentences)

    {weatherOz} aims to facilitate access and download weather and
    climate data for Australia from Australian data sources. Data are
    sourced from from the Western Australian Department of Primary
    Industries and Regional Development (DPIRD) and the Scientific
    Information for Land Owners (SILO) API endpoints and the Australian
    Government Bureau of Meteorology's (BOM) FTP server.

-   Who is the target audience and what are scientific applications of
    this package?

    The target audience for this package is researchers, industry
    stakeholders and endusers who need to find, access and download and
    analyse weather and climate data from Australian data sources.

-   Are there other R packages that accomplish the same thing? If so,
    how does yours differ or meet [our criteria for
    best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

    No available package has the functionality and capabilities to find,
    access and download weather and climate data for Australia from
    multiple Australian data sources.

    The {bomrang} package, currently archived and unsupported due to
    Australian Government Bureau of Meteorology (BOM) policy changes,
    has functionality to source data from BOM. Some of the existing
    functionality that is permitted by the BOM has been incorporated
    into {weatherOz}.

-   (If applicable) Does your package comply with our [guidance around
    *Ethics, Data Privacy and Human Subjects
    Research*](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

    Not applicable.

-   If you made a pre-submission inquiry, please paste the link to the
    corresponding issue, forum post, or other discussion, or @tag the
    editor you contacted.

    No pre-submission inquiry submitted.

-   Explain reasons for any [`pkgcheck`
    items](https://docs.ropensci.org/pkgcheck/) which your package is
    unable to pass.

    Currently the {weatherOz} passes all `pkgcheck` items.

## Technical checks

Confirm each of the following by checking the box.

-   [x] I have read the [rOpenSci packaging
    guide](https://devguide.ropensci.org/building.html).
-   [x] I have read the [author
    guide](https://devdevguide.netlify.app/authors-guide.html) and I
    expect to maintain this package for at least 2 years or to find a
    replacement.

This package:

-   [x] does not violate the Terms of Service of any service it
    interacts with.
-   [x] has a CRAN and OSI accepted license.
-   [x] contains a [README with instructions for installing the
    development
    version](https://ropensci.github.io/dev_guide/building.html#readme).
-   [x] includes [documentation with examples for all functions, created
    with
    roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
-   [x] contains a vignette with examples of its essential functions and
    uses.
-   [x] has a [test
    suite](https://ropensci.github.io/dev_guide/building.html#testing).
-   [x] has [continuous
    integration](https://ropensci.github.io/dev_guide/ci.html),
    including reporting of test coverage.

## Publication options

-   [x] Do you intend for this package to go on CRAN?

-   [ ] Do you intend for this package to go on Bioconductor?

-   [ ] Do you wish to submit an Applications Article about your package
    to [Methods in Ecology and
    Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)?
    If so:

<details>

<summary>MEE Options</summary>

-   [ ] The package is novel and will be of interest to the broad
    readership of the journal.
-   [ ] The manuscript describing the package is no longer than 3000
    words.
-   [ ] You intend to archive the code for the package in a long-term
    repository which meets the requirements of the journal (see [MEE's
    Policy on Publishing
    Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
-   (*Scope: Do consider MEE's [Aims and
    Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html)
    for your manuscript. We make no guarantee that your manuscript will
    be within MEE scope.*)
-   (*Although not required, we strongly recommend having a full
    manuscript prepared when you submit here.*)
-   (*Please do not submit your package separately to Methods in Ecology
    and Evolution*)

</details>

## Code of conduct

-   [x] I agree to abide by [rOpenSci's Code of
    Conduct](https://ropensci.org/code-of-conduct/) during the review
    process and in maintaining my package should it be accepted.

**Comment by bozaah** [comment]
@ropensci-review-bot check package

**Comment by bozaah** [comment]
Thank you! We have addressed the✖️ issues: dealt with `terra::plot()` export, reduced complexity of `get_dpird_summaries()` and `find_nearby_stations()`, and we expect that users should be aware of `get_station_metadata()` if loading both weatherOz and stationaRy. Users can use `::` to select a function from the intended package and/or utilities such as the {conflicted} package.

@ropensci-review-bot check package

**Comment by bozaah** [comment]
@ropensci-review-bot check package

**Comment by noamross** [comment]
@ropensci-review-bot assign @ldecicco-USGS  as editor

**Comment by noamross** [comment]
@ropensci-review-bot assign @ldecicco-USGS as editor

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot seeking reviewers

**Comment by bozaah** [comment]
Dear @ldecicco-USGS,
Thank you for taking up the editor role for our package. I appreciate yours and @JanLauGe's time working on this. 

I am writing to mention that I will be on leave until the first week of November so I will be somehow slow and/or unresponsive to queries from you and the package reviewers. I will address the comments and necessary edits upon my return. Thank you!

**Comment by JanLauGe** [comment]
Apologies for the delay in getting this off the ground. I'd love to kick this off this week if that is still okay with everybody?

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot assign @rogerssam as reviewer

**Comment by rogerssam** [comment]
@ropensci-review-bot check package

**Comment by rogerssam** [comment]
HI all, here is my review.

## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

-   **Briefly describe any working relationship you have (had) with the package authors.**
    -   No working relationship with authors to date.
-   ☒ As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor *before* starting your review).

#### Documentation

The package includes all the following forms of documentation:

-   ☒ **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
-   ☒ **Installation instructions:** for the development version of package and any non-standard dependencies in README
-   ☒ **Vignette(s):** demonstrating major functionality that runs successfully locally
-   ☒ **Function Documentation:** for all exported functions
-   ☒ **Examples:** (that run successfully locally) for all exported functions
-   ☒ **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

-   ☒ **Installation:** Installation succeeds as documented.
-   ☒ **Functionality:** Any functional claims of the software been confirmed.
-   ☒ **Performance:** Any performance claims of the software been confirmed.
-   ☒ **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
-   ☒ **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 6

-   ☒ Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer (“rev” role) in the package DESCRIPTION file.

------------------------------------------------------------------------

### Review Comments

Overall the package appears to be well developed, robust and meets a need of providing access to weather data in Australia. Some additional comments:

-   Checking for the example API key is a nice UX touch.
-   The vignettes are clear, and show a good demonstration of the functionality of the package.
-   The main functions follow a clear convention, which provides obvious entry points for new users.
-   Great to see near complete test coverage.
-   I am familiar with the difference between patched point and data drills from the SILO data, but I expect new users would not be, so perhaps the titles of those functions could be expanded? For example `Get DataDrill (Gridded) Weather Data From SILO` and `Get PatchedPoint (Station) Weather Data From SILO` or similar. I think it makes sense to have the function names matching the SILO API, but I think the titles could provide a little more clarity. I also realise that the detail is available within the function documentation, however that’s an extra step for users to find the right function that they need.

In the current state, I think the package is very good and perfectly usable, however below are some additional suggestions for improvements. I will add some issues on the repo for consideration by the authors.

-   I wonder if it’s worth including some sort of validation on the `api_key` (email) input to the SILO functions? Obviously [email address validation is not trivial](https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression) but at present entry of `abc` as the api\_key/email is valid input. Some obvious errors are caught by SILO (e.g. `---@...`) but others are not. I will leave it as a decision for the authors.
-   I think it would be useful for the `get_station_metadata()` function to have the ability to return a single station metadata, rather than just all of them. There could be a `station` argument set to `"all"` by default.

Overall, great work, and I will be personally using it shortly for some of my work!

Thanks, 
Sam Rogers

**Comment by bozaah** [comment]
Dear @ldecicco-USGS,
We have addressed the feedback from @rogerssam which we appreciate a lot. We also took on board the comments regarding the name of functions requesting SILO data and the documentation on the data types accepted as `station_code` by the SILO functions. We will address those once we receive the review from @JanLauGe if that is acceptable. Much appreciated, Rodrigo.

**Comment by JanLauGe** [comment]
## Package Review

- **Briefly describe any working relationship you have (had) with the package authors.**
No working relationship with authors to date.
- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions
- [x] **Examples:** (that run successfully locally) for all exported functions
- [x] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [ ] **Functionality:** Any functional claims of the software been confirmed.
I have not tested all functions yet due to getting stuck with the unit tests.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
Currently I'm getting test errors on my local machine. Happy to work with you to figure out what is going on.
- [x] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 5

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

-----------------

### Additional comments:

* [this](https://github.com/DPIRD-FSI/weatherOz/blob/3dfba0b0720db7bb5738afa9d1169b07d8abdbc0/R/get_station_metadata.R#L123) check for whether the API key has been provided currently doesn't work with the examples because both `NULL` and an empty string resulting from `Sys.getenv("DPIRD_API_KEY")` passes the test. That means that if a new user just uses the function from the example they end up with a relatively cryptic error. Can you add a test or conditition for `NULL` and empty string?

* I agree with @rogerssam that email address validation would be a good addition. To play it safe, the package could produce a `message()` when detecting an invalid email address instead of `stop()`-ing with an error. [Example](https://www.r-bloggers.com/2012/07/validating-email-adresses-in-r/) of an email address validation regex.

* Running tests required installing the `vcr` package for me which is not listed as dependency.

* Currently some tests are failing for me locally (iOS). I'm attaching the test report below.

```
...
trying URL 'ftp://ftp.bom.gov.au/anon/gen/fwo/IDW14199.xml'
Content type 'unknown' length 546501 bytes (533 KB)
==================================================
file downloaded to:/var/folders/43/c5m9cb696l7fgnfsls66r1f400th2k/T//RtmpbdumdW/file6cd638754f36.gif
file downloaded to:/var/folders/43/c5m9cb696l7fgnfsls66r1f400th2k/T//RtmpbdumdW/file6cd61da37f2f.gif
[ FAIL 3 | WARN 0 | SKIP 0 | PASS 396 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-get_dpird_summaries.R:235:15'): get_dpird_summaries() returns hourly values ──
Error: 

================================================================================
An HTTP request has been made that vcr does not know how to handle:
GET https://api.dpird.wa.gov.au/v2/weather/stations/summaries/hourly?stationCode=BI&startDateTime=2017-10-28&endDateTime=2017-11-01&interval=hourly&select=stationCode%2CstationName%2Cperiod%2Cwind&group=all&includeClosed=false&api_key=<<<dpird_api_key>>>&offset=0&limit=74
vcr is currently using the following cassette:
  - <local path redacted>/weatherOz/tests/fixtures/dpird_summaries_hourly.json
    - record_mode: once
    - match_requests_on: method, uri
```

**Comment by yabellini** [comment]
Hi @rogerssam, @arhepworth, @syntrix, @becoleary. rOpenSci Community Manager here.  
If you want to join our Slack, I can send an invitation.  Please share with me what email you want to use.  You can write me to yabellini@ropensci.org.  Thank you!

**Comment by ldecicco-USGS** [comment]
Thanks so much @JanLauGe! If you aren't on the rOpenSci slack, please see @yabellini 's message above

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/598#issuecomment-18659958772 time 5

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/598#issuecomment-1865995877 time 5

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/598#issuecomment-1832968340 time 6

**Comment by bozaah** [comment]
Thank you for your comments and feedback. I am working through the changes and should have my reply by Thursday. Much appreciated, Rodrigo

**Comment by bozaah** [comment]
Thank you for your time reviewing `{weatherOz}` @JanLauGe and @rogerssam, we appreciate that. Your comments have helped us improve the package and hopefully the user experience with `{weatherOz}`. I have collated the responses to the points you have raised below:

- We have added an email validation check as suggested. Functions will still return an error and `stop` if a valid `api_key` is not provided. Closed issue 49 with [commit 3dfba0b](https://github.com/DPIRD-FSI/weatherOz/commit/3dfba0b0720db7bb5738afa9d1169b07d8abdbc0).

- We have maintained SILO functionality with the same names (i.e., `get_data_drill()` and `get_patched_point()`). As noted, the function documentation is clear on the API endpoints queried and there is also the [SILO vignette](https://dpird-fsi.github.io/weatherOz/articles/weatherOz_for_SILO.html) which details the functionality and has additional information on the endpoints, variables and query output types. We believe this provides the user a clear view of the functionality.

- We have added a check to functions that required the `station_code` argument (i.e., `get_dpird_extremes()`, `get_dpird_minute()`, `get_dpird_summaries()`, `get_patched_point()` and `get_patched_point_apsim()`) so that only a character string type is accepted. [commit ae26fe9](https://github.com/DPIRD-FSI/weatherOz/commit/ae26fe90b5918ea5f3f57975ba5d174ed54cff77).

-  Added functionality to `get_station_metadata()` so that it returns the metadata for only one station if required. Closed issue 51 with [commit 8166c92](https://github.com/DPIRD-FSI/weatherOz/commit/8166c92f63ed138ccfed966a09e9537a35324b67).

- Added check to the functions that require the `api_key` argument (i.e., `get_dpird_*()`, `get_data_drill*()`, `get_patched_point*()`, `find_nearby_stations()` and `get_station_metadata()`) so that missing, empty or null returns an error. [commit f86b949](https://github.com/DPIRD-FSI/weatherOz/commit/f86b9491dec556a3f0e4c7a11ac6d71b18880d96).

- We have listed `{vcr}` in the [Suggests section](https://github.com/DPIRD-FSI/weatherOz/blob/ae26fe90b5918ea5f3f57975ba5d174ed54cff77/DESCRIPTION#L168) of the DESCRIPTION as noted in the [rOpenSci HTTP testing in R book](https://books.ropensci.org/http-testing/vcr.html). We are happy to adjust that if there is better way to address this.
   
- The test error @JanLauGe is due to the date range used in the query (and consequently saved into the `{vcr}` cassete). The DPIRD endpoint with `hourly` data (and also `15min` and `30min` intervals) only accepts dates up to the 1st day of the  last year (in 2024 this is `2023-01-01`). The function help describes this limitation when the `interval` argument is shorter than `daily`. I have updated the `testthat.R` and saved a new `{vcr}` cassete to reflect that and I have no errors on my current checks/tests. Thank you for picking this up!

I am currently running the checks and tests locally on MacOS and Windows. I have also updated the Github CI/tic workflows and I am hopeful it will work. I have added @JanLauGe and @rogerssam to the list of authors [commit a00dbba](https://github.com/DPIRD-FSI/weatherOz/commit/a00dbba32814559babd235d4684234ed6ba3ec6b) Again, thank you for your feedback, I am sure users will benefit from your comments!

I will create a PR so that @adamhsparks can check for issues I might have missed (or created) while editing `{weatherOz}` in line with your feedback. We will also update the `NEWS.md` with the most recent changes once the merge is accepted. 

Please let me know if there is anything else you would like us to take a look or rectify.

Thank you!

**Comment by bozaah** [comment]
@ropensci-review-bot check package

**Comment by rogerssam** [comment]
Thanks @ldecicco-USGS. No concerns from me.

Well done @bozaah and @adamhsparks!

**Comment by bozaah** [comment]
I ran the package check before merging the PR! Lets try again,  @ropensci-review-bot check package

**Comment by bozaah** [comment]
@ropensci-review-bot check package

**Comment by ldecicco-USGS** [comment]
@JanLauGe , any comments on the response to review?

**Comment by JanLauGe** [comment]
Thanks for the ping, no concerns here. Great package and glad we had a few points where the feedback was useful!

**Comment by ldecicco-USGS** [comment]
Whoo hoo, thanks @JanLauGe  and @rogerssam - we really appreciate the time and effort it takes to put together a nice review. @bozaah - congratulations 🎉 on a great and useful package!

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot approve weatherOz

**Comment by bozaah** [comment]
@ropensci-review-bot finalize transfer of weatherOz

**Comment by bozaah** [comment]
Hi @ldecicco-USGS, I have made the transfer and tagged the bot to complete the process. We will work through the other items in the checklist next. We have also drafted a JOSS manuscript for submission, where can we find the next steps in the process please? Lastly, yhank you again for supporting us during the review and our appreciation to @JanLauGe and @rogerssam for their time and input improving our package.

**Comment by ldecicco-USGS** [comment]
All I know is:
https://joss.readthedocs.io/en/latest/submitting.html

And mention in the submission you've gone through an rOpenSci review, I'd put a link to this github issue. I'll double check there aren't more specific rOpenSci recommendations.
