### ISSUE TITLE
dendroNetwork

### ISSUE THREAD

**Issue by RonaldVisser** [ropensci/software-review#627]
**Date accepted:** 2024-04-25

Submitting Author Name: Ronald M. Visser
Submitting Author Github Handle: @RonaldVisser
Repository:  https://github.com/RonaldVisser/dendroNetwork
Version submitted: 0.5.0
Submission type: Standard
Editor: @ldecicco-USGS
Reviewers: @kaijagahm, @gzach93

Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: dendroNetwork
Type: Package
Title: Create networks of dendrochronological series using pairwise similarity
Version: 0.5.0
Authors@R: 
    c(person(given ="Ronald", 
            family = "Visser", 
            email = "r.m.visser@saxion.nl", 
            role = c("aut", "cre"),
            comment = c(ORCID = "0000-0001-6966-1729")),
    person(given = "Angelino", 
            family ="Salentino",
            role = "ctb",
            comment = c(ORCID = "0000-0002-4763-3943")),
   person(given = "Andy", 
            family ="Bunn",
            role = "ctb",
            comment = c(ORCID = "0000-0001-9027-2162")))
Maintainer: Ronald Visser <r.m.visser@saxion.nl>
Depends: R (>= 3.5.0)
Imports: 
    dplR (>= 1.7.2),
    igraph,
    stringr,
    reshape2,
    RCy3,
    dplyr,
    RColorBrewer,
    tidyr,
    foreach,
    magrittr,
    doParallel,
    lifecycle, 
    stats,
    grDevices
Description: This package makes it easy to create dendrochronological networks based on the similarity between tree-ring series or chronologies. It includes various functions to compare tree-ring curves building upon dplR. The networks can be used to visualise and understand the relations between tree-ring curves. These networks are also very useful to estimate the provenance or wood-use within a structure/context/site.
License: GPL (>= 3)
Encoding: UTF-8
LazyData: true
RoxygenNote: 7.3.1
Suggests: 
    testthat (>= 3.0.0)
Config/testthat/edition: 3
Roxygen: list(markdown = TRUE)

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [x] scientific software wrappers
	- [x] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
The software deals with the analysis of dendrochronological data and aims the help to study, understand and visualize patterns in the data using network analyses. The software combines R with Cytoscape.

-   Who is the target audience and what are scientific applications of this package?
Dendrochronologist. The scientific application lies in the analyses and visualization of large datasets using networks. The method has been applied before to determine the provenance of wood from archaeological contexts, but can also be used to determine other patterns based on the similarity between tree-ring series or even other time series.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
- No, none as far as I know.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
NA
-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

I tried to run pkgcheck, but it failed with the following feedback:

Error in vapply(tag_data, function(i) i$keyword, character(1L)) : 
  values must be length 1,
 but FUN(X[[12]]) result is length 2

I have absolutely no idea why....

The same error occurs locally and using github action.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by ldecicco-USGS** [comment]
I'm guessing the issue is that `RCy3` is only on Bioconductor. The mentions I found in the rOpenSci guide:

https://devguide.ropensci.org/building.html?q=Biocond#pkgdependencies

And:
"If you develop a package depending on or intended for Bioconductor, you might find [biocthis](https://lcolladotor.github.io/biocthis/index.html) relevant."

I'll poke around more and see if I can find other recent submissions that used Bioconductor packages.

**Comment by mpadge** [comment]
Sorry @ldecicco-USGS and @RonaldVisser, that was a bug with Bioc installs on our side. Checks should appear in a moment.

**Comment by ldecicco-USGS** [comment]
Thanks for the submission @RonaldVisser ! Looks like a neat package. 

Before we can proceed you'll need to get continuous integration set up. I'd start by trying:
https://usethis.r-lib.org/reference/github_actions.html#use-github-action-check-standard-


That might work - I haven't used Bioconductor packages in awhile, so I'm not 100% sure. If that doesn't work, then you could try:
https://rdrr.io/bioc/biocthis/man/use_bioc_github_action.html

The other "X" items above should be pretty straightforward to address, but let me know if you have any questions.

The error on the build is:

```
Quitting from lines 21-44 [flowchart_workflow] (dendroNetwork_use.Rmd)
Error: processing vignette 'dendroNetwork_use.Rmd' failed with diagnostics:
there is no package called 'DiagrammeR'
--- failed re-building ‘dendroNetwork_use.Rmd’
```

If `DiagrammeR` isn't used in any of the package functions, you'll want to add it to "Suggests" for that vignette to be generated.

**Comment by RonaldVisser** [comment]
Thanks for the compliment! Thank you for the comments and help!

I have done some updating of various functions, added some tests and the continuous integration (github actions R-CMD / pkgcheck) seems to be working fine. According to pkgcheck it now checks all the boxes :) 

Due to the various edits, I released a new release (0.5.1), with changes described in the NEWS-file.

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot check package

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot assign @ldecicco-USGS as editor

**Comment by ldecicco-USGS** [comment]
### Editor checks:

- [ ] **Documentation**: The package has sufficient documentation available online (README, pkgdown docs) to allow for an assessment of functionality and scope without installing the package. In particular,
    - [ ] Is the case for the package well made?
    - [ ] Is the reference index page clear (grouped by topic if necessary)?
    - [ ] Are vignettes readable, sufficiently detailed and not just perfunctory?
- [x] **Fit**: The package meets criteria for [fit](https://devguide.ropensci.org/policies.html#package-categories) and [overlap](https://devguide.ropensci.org/policies.html#overlap).
- [x] **Installation instructions:** Are installation instructions clear enough for human users?
- [x] **Tests**: If the package has some interactivity / HTTP / plot production etc. are the tests using [state-of-the-art tooling](https://devguide.ropensci.org/building.html#testing)?
- [x] **Contributing information**: Is the documentation for contribution clear enough e.g. tokens for tests, playgrounds?
- [x] **License:** The package has a CRAN or OSI accepted license.
- [x] **Project management**: Are the issue and PR trackers in a good shape, e.g. are there outstanding bugs, is it clear when feature requests are meant to be tackled?
---

#### Editor comments

I was able to run the example functions from the readme and vignette. It would very helpful to push a compiled `pkgdown` site to a GitHub Page. You can set that up with:
```
usethis::use_pkgdown_github_pages()
```
Setting up a pkgdown site should take care of most of the "Documentation " subtasks. The other sub-category that could be improved is "not just perfunctory" vignettes. Perhaps you could take the contents of the "paper.md" and put that same information in a vignette? 

I would also ask that you take a look at the following packages and make sure there's not specific overlap:

https://github.com/AndyBunn/dplR
https://github.com/hanecakr/fellingdateR
https://github.com/ropensci/MtreeRing

There's a good chance I'd be asking authors from those packages to do a review. I do not know enough about tree ring science to understand where the overlap might fall.


---

**Comment by RonaldVisser** [comment]
Thank you for your helpful comments! More steps to make my package better :)

The paper is there to submit to JOSS in a later stage, but I have added an extra Vignette and I'll think about  developing more Vignettes.

I have created a pkgdown website: [https://ronaldvisser.github.io/dendroNetwork/](https://ronaldvisser.github.io/dendroNetwork/)  and that was and interesting and fun thing to do :)

There is no overlap with the packages you mentioned:

- https://github.com/AndyBunn/dplR: this is for other purposes, mainly general analyses of tree-ring material. I am also a contributor to that package. In addition, my package uses that packages as a dependency.
- https://github.com/hanecakr/fellingdateR: I know that package and the author. That package serves another goal: mainly to analyse felling dates, while my package aims at making the use of network analysis accessible for dendrochronology
- https://github.com/ropensci/MtreeRing: This package is for measuring tree rings and not for visualising patterns in networks.
I believe that the dendroNetwork package can work very well with these packages together, but it adds new functionality to the available R-packages and I have tried to explain that in the paper (for JOSS) I have added in the repository.  
Oh, for your information, there are more packages in R for dendrochronology and I have compiled a list in the past: https://ronaldvisser.github.io/Dendro_R/

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot assign @kaijagahm as reviewer

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot assign @gzach93 as reviewer

**Comment by kaijagahm** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide*

-   **Briefly describe any working relationship you have (had) with the package authors.**
-   I have no relationship with the package author.
-   ☒ As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor *before* starting your review).

#### Documentation

The package includes all the following forms of documentation:

-   ☒ **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README

-   ☐ **Installation instructions:** for the development version of package and any non-standard dependencies in README

    Some functionality of the package depends on having Cytoscape installed. This is briefly mentioned in the README, but I would recommend being a little more explicit that this is an external program that will need to be installed and that the Cytoscape-related portions of the package won’t work without it. You might also mention that CyREST should be automatically installed with Cytoscape, and that if users encounter errors with CyREST they should try restarting their computer, maybe downloading CyREST separately, etc.

-   ☐ **Vignette(s):** demonstrating major functionality that runs successfully locally

    Vignettes exist, but `vignette(package = "dendroNetwork")` returns no results, `browseVignettes(package = "dendroNetwork")` returns no results, and the vignettes aren’t listed under `?dendroNetwork`. Make sure to include the vignettes when you build the package, and see <https://r-pkgs.org/vignettes.html> for reference on how to incorporate vignettes.  
      
    Some of the vignettes (cytoscape.Rmd) do seem to run locally (and they are a bit clearer than the README about needing to install Cytoscape separately!) However, dendroNetwork\_use.Rmd fails to run locally because it needs citations… Maybe I’m just not understanding how to run a vignette properly? Maybe I need all the files there? Sorry if this is not a failure of the package but just a failure of me knowing how to run vignettes locally!

-   ☒ **Function Documentation:** for all exported functions

-   ☐ **Examples:** (that run successfully locally) for all exported functions

Example in `wuchswerte` fails because object `anos1` is not found.

    library(dendroNetwork)
    data(hol_rom)
    dplR::as.rwl(apply(anos1, 2, wuchswerte))
    #> Error in eval(expr, envir, enclos): object 'anos1' not found

<sup>Created on 2024-03-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

`t_value` doesn’t return anything to console–consider including an explicit return statement.

    library(dendroNetwork)
    t_value(0.5, 100) # no output
    a <- t_value(0.5, 100)
    a
    #> [1] 5.744563

<sup>Created on 2024-03-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

`cyto_create_gn_style(g_hol, gn_coms = g_hol_gn)` fails when run as part of the example for `cyto_create_gn_style`. Seems to be unable to load a file?

    library(dendroNetwork)
    data(hol_rom)
    sim_table_hol <- sim_table(hol_rom)
    g_hol <- dendro_network(sim_table_hol)
    hol_com_cpm_k3 <- clique_community_names(g_hol, k = 3)
    cyto_create_cpm_style(g_hol, k = 3, com_k = hol_com_cpm_k3)
    #> Error: Don't know how to read file:/private/var/folders/xy/lqbp515s27q8v1drkll9gynw0000gr/T/RtmppMCfZy/reprex-172671e49826-large-unau/

<sup>Created on 2024-03-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

`cyto_create_cpm_style` fails similarly.

    library(dendroNetwork)
    data(hol_rom)
    sim_table_hol <- sim_table(hol_rom)
    g_hol <- dendro_network(sim_table_hol)
    hol_com_cpm_k3 <- clique_community_names(g_hol, k = 3)
    cyto_create_cpm_style(g_hol, k = 3, com_k = hol_com_cpm_k3)
    #> Error: Don't know how to read file:/private/var/folders/xy/lqbp515s27q8v1drkll9gynw0000gr/T/RtmppMCfZy/reprex-172625011c73-alive-lark/

<sup>Created on 2024-03-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

-   ☐ **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

Missing contribution guidelines. Includes URL, BugReports, and Maintainer.

#### Functionality

-   ☒ **Installation:** Installation succeeds as documented.
-   ☒ **Functionality:** Any functional claims of the software been confirmed.
-   ☒ **Performance:** Any performance claims of the software been confirmed.
-   ☐ **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.

I see that there are tests set up, but I am not familiar with how to run the tests for someone else’s package on my own local machine. If anyone can provide guidance on this, I’d be happy to take a look! I have run tests for my own package before, but never for a package I’ve installed.

-   ☐ **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Title: good

codemetar: I’m not familiar with this.

Platforms: runs on Mac; I can’t comment on other systems.

Package API: function names are in snake\_case and are reasonably logical. Could be nice to preface them all with a common thing like `dendro_` and make some of them shorter, but effort has already been made to make them short and consistent. I appreciate that the cytoscape-interface functions are all named with `cyto_`at the beginning, for instance.

Input checking: There is some input checking, and the error messages returned seem sensible. I would suggest doing a little more input checking, for example making sure that the network objects being passed to the functions are actually igraph network objects as expected. This goes hand in hand with my recommendation that you be a bit more specific about what data format is expected from users of the package. Keep in mind data types etc. and think about which ones will or won’t break your functions. I like to use the `checkmate` package for fast and easy argument checking, but there are many options including just more base R checks.

CITATION file: good

README etc: generally, multiple points of entry are done well. There is redundancy in where the information is presented, and I was mostly able to find out about the package and its core workflow through the README as well as the vignettes.

Documentation website: ?

Consider @family tag for function grouping

Estimated hours spent reviewing: 4

-   ☒ Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer (“rev” role) in the package DESCRIPTION file.

------------------------------------------------------------------------

### Review Comments

1.  I am coming to this review without any prior understanding of dendrochronology. Therefore, it would be helpful if you could provide more information about the data types. For example, `?hol_rom` tells me that this dataset contains dendrochronological site chronologies. I don’t actually know what a “site chronology” is. What is an object of class “rwl”, and how would I go about making sure that an object I’m feeding into this function has class “rwl” (or is it okay if it’s just a data frame)? What does a single row in this dataset represent? What does a single column represent? What do the column names mean? It’s possible that anyone who would be using this package would already understand these things, but I think there’s no harm in being more explicit. When I go to use a package, typically my first question is “If I wanted to use this package on my data, what would my data have to look like, exactly, in order for the functions to work?”

2.  Regarding the documentation for `sim_table`: I think I would understand this better if I understood the the data better, as described in 1). It seems like you’re saying that `trs1` (`hol_rom`, in this example) represents a single tree ring series (or is it multiple series? I can’t tell). `trs2` is optional. I did some experimenting and found that if you don’t specify `trs2`, the function ends up comparing `trs1` to itself; that is, `identical(sim_table(hol_rom), sim_table(hol_rom, hol_rom))` is `TRUE`. In the description for the `trs1` argument, maybe specify that behavior, instead of saying “to be compared with `trs2`.

3.  Carrying on with the theme of me being naive to the domain: I don’t understand what `last_digit_radius` does. What is a “series name” and what is the “radius of the tree-ring series”? What would be the units of the radius? Why does this argument matter? Again, if the answers to some of these questions would be obvious to domain-familiar users of your package, then maybe it’s not necessary to define them, but I was wondering.

4.  Make sure to specify in multiple places that Cytoscape has to be not only installed but actually running when you use the functions that relate to it.

5.  It would be nice if there was an example of how to use the package on large datasets. I recognize, though, that including a large dataset is probably not practical. Maybe use a small dataset as an example but still run it in parallel, using `tic()` and `toc()` to demonstrate the time difference? In the given example, it wasn’t clear that the object `network` in the example code wasn’t a real object and that the code wouldn’t actually run.

6.  `cyto_create_cpm_style` maybe didn’t work for me? I’m not exactly sure what was supposed to happen, but I didn’t see any colors or styling appearing, just black and white. I can provide more details/screenshots if that would help.

Some more detailed comments on the pre-cytoscape functions (some of this is maybe overly nitpicky, but it was my thought process as I was working through the functions!)

**Comment by RonaldVisser** [comment]
Hi @kaijagahm, thank you for the review and your detailed comments. These are very helpful for improving the package and the documentation, which makes me happy. I am looking forward to address the various things you pointed out and I hope to do this as soon as possible.

**Comment by kaijagahm** [comment]
You're very welcome! It was fun to explore this. I know my comments are a bit all over the place; I hope they are navigable. Feel free to ask if you encounter any confusion. 

Except for some concerns over the examples running and one of the functions not showing colors in Cytoscape, and some documentation tweaks, most of my comments were around the margins and the package seems to be doing pretty well at its core functionality. I look forward to seeing how this develops!

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/627#issuecomment-1993235710 time 4

**Comment by gzach93** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [X] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [X] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README

I think the author did a great job connecting their R package to the already existing R packages specifically created for their field.

- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README

The installation instructions were easy to follow and I was able to install the package and realted software needed. 

It seems like the audience for this package would be new researchers to dendrology that are looking to create dendrochonological networks. If this is the intended audience maybe the author can add  a little more about what Cytoscape is and does or provide a small summary and where the reader can find more resources? I want to make sure that I understand but is Cytoscape mainly used for the visualization after this R packages formats the data and run the network analyses?

- [ ] **Vignette(s):** demonstrating major functionality that runs successfully locally

Could you add the data description for the example data in the vignettes? I see it in RING_Visser_2021.Rd, but it might be good to move that into the vignette.

Can more specific details about what the code is doing be added? Consider also adding a brief description of things like the Girvan-Newman algorithm or more technical terms. Again I am assuming that this package is trying to create an easy pathway for researchers getting into this sort of analysis.   


- [X] **Function Documentation:** for all exported functions
- [ ] **Examples:** (that run successfully locally) for all exported functions

The t_value function could use a return function at the end of it. The example of the t_value function does not output results right now.

The wuchswerte function example, I think, require a dataset "anos1" from the dplR package. However, in order to use this dataset users have to visit https://opendendro.github.io/dplR-workshop/ to get started. Is it possible to make this data more accessible or use another dataset? 

- [X] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [X] **Installation:** Installation succeeds as documented.
- [X] **Functionality:** Any functional claims of the software have been confirmed.
- [X] **Performance:** Any performance claims of the software have been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.

I am not sure how to run these tests.

- [X] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 4

- [X] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

1) From my read through, I assumed that the audience was a new dendrologist of someone less familiar with creating these analyzes and this package creates an easier enterance point to help them. It think that this package does pretty good with this. However, maybe the vingettes can be expanded a little, offering another example dataset to work with and added definition for more field related jargon. 

2) In the vignettes can you add a description of the example data. It might help new users better connect their datasets to the example data and think about the correct formatting needed.

3) I am not a dendrologist and I am not familiar with Cytoscape, so I am not sure if this is a familiar enough program where users do not need more information about what this program is used for or not. But, I think it might be useful to add more information about what Cytoscape is and some of the uses it has.

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/627#issuecomment-2037644081 time 4

**Comment by ldecicco-USGS** [comment]
Thanks @gzach93! One way to run the tests (these are the "testthat" tests in the "test" folder) is to run `devtools::test()`. There are a few other options (you could go into the test folder and run them line-by-line even). The comment "Unit tests cover essential functions of the package and a reasonable range of inputs and conditions." means you are looking at the set of tests that the author includes to make sure they are testing a good-enough set of conditions on their functions. From the automated ropensci-bot, we know "Package coverage is 91.4%.". That's pretty good! It means 91.4% of the code is somehow tested in the testthat folder. The reviewer's job is just to make sure those tests seem adequate (which _is_ subjective, but you can generally get a pretty good idea if the author's doing their due-diligence). If you knew of some important edge-cases for example, you would maybe want the developers to be testing those conditions. 

@RonaldVisser you can now start addressing the reviews!

**Comment by RonaldVisser** [comment]
## Response to review Zachary Gajewski (gzach93)

Thank you for your review, @gzach93. I am happy that you were positive about many things, but also for finding things to improve the package! Some things were already corrected before receiving your review and I am sorry for already updating while waiting for your review.

Documentation

Installation instructions: Thanks for noticing that. I have added a description of Cytoscape to the README and the vignettes: dendroNetwork and Cytoscape, including a link to the [Cytoscape-website](https://cytoscape.org/what_is_cytoscape.html)., see [commit](https://github.com/RonaldVisser/dendroNetwork/commit/bc1bd46c1b413350dd333e826503f72af9005b2f).

Vignettes: 

I have added a vignette on dendrochronological data, see [commit](https://github.com/RonaldVisser/dendroNetwork/commit/aa29067c9000467df09f22d9ed4948697fc8d250).

Links to a better explanation of the Girvan-Newman Algorithm and CPM were already added earlier, based on the review by @kaijagahm, see [response and commit](https://github.com/ropensci/software-review/issues/627#issuecomment-2027514872)

Examples: 

Thanks for also noticing that t_value() was not outputting to console. This was already corrected, based on the other review: see [commit](https://github.com/RonaldVisser/dendroNetwork/commit/d72bd4ca44a13628ca23e71389973013bd5c2743). 

The references to the anos1 dataset was also already corrected, see [commit](https://github.com/RonaldVisser/dendroNetwork/commit/d72bd4ca44a13628ca23e71389973013bd5c2743)

 Automated tests: see [response](https://github.com/ropensci/software-review/issues/627#issuecomment-2027514872) to the review by [kaijagahm](https://github.com/kaijagahm)

You were added as reviewer to the DESCRIPTION-file, see [commit](https://github.com/RonaldVisser/dendroNetwork/commit/65d636b7e2cc77a17499ae4030f8e3cdd52f82a2)

Review Comments

Thanks for pointing this out. I have update various things in the readme and the vignettes. I hope that this is now more clear

I have added a vignette on the data, so this should help.

I have added some description for Cytoscape and also some links to find more help.

I would like to explain that a [dendrology](https://en.wikipedia.org/wiki/Dendrology) is not the same as [dendrochronology](https://en.wikipedia.org/wiki/Dendrochronology). Both are tree related, but the latter is aimed at tree-rings and the temporal patterns and the former more on trees in general. This confusion is very common, since these words look very similar.

**Comment by ldecicco-USGS** [comment]
Hi @gzach93 and @kaijagahm 

Do you feel that the changes and updates have addressed your concerns? 

If so, see:
https://devdevguide.netlify.app/approval2template

**Comment by gzach93** [comment]
Hi @RonaldVisser thank you for going through and addressing all my comments! 

## Reviewer Response #### Final approval (post-review) - [X] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**

**Comment by ldecicco-USGS** [comment]
Thanks again @gzach93 and @kaijagahm for the reviews and @RonaldVisser for the submission!

**Comment by ldecicco-USGS** [comment]
@ropensci-review-bot approve dendroNetwork

**Comment by kaijagahm** [comment]
## Reviewer Response

#### Final approval (post-review)

- [ X] **The author has responded to my review and made changes to my satisfaction. I recommend approving this package.**



Estimated hours spent reviewing: 4.5 (total, not just for this step)

**Comment by RonaldVisser** [comment]
@ropensci-review-bot finalize transfer of dendroNetwork

**Comment by RonaldVisser** [comment]
Thanks @ldecicco-USGS for your excellent role as editor! And thanks again @kaijagahm and @gzach93 for your wonderful reviews.

The package is now transferred to ROpenSci and I have addressed all to do's 

I'd be happy to write a blog post about this packages @ropensci/blog-editors

**Comment by steffilazerte** [comment]
Hi @RonaldVisser!

I'm excited to hear that you're interested in writing a blog post for us!

As mentioned above, we have two types of blog posts: either [an introduction to your package featuring technical details](https://ropensci.org/tech-notes/) for a technical audience or [a longer post with some narrative](https://ropensci.org/blog/) about its development or something you learned, and possibly an example of its use for a broader readership. The difference between a technote and a blog post is more about the style and content then length, but technical posts are often shorter than blog posts (no requirement either way). 

To contribute a post, we'll have you open a PR to the roweb3 repository. About a week or two before our publication date, you can ping me and I'll review the post and give you some suggestions for content and style. You'll consider my feedback, make any changes you'd like to make, and then we merge and publish! We have a flexible timeline right now, so when every you're ready is good for us. However, if you work better with a deadline, we could set a deadline of the last week of May for the draft, expecting to publish the first week of June (or earlier!).

You can read more about the details of writing an rOpenSci blog post here: https://blogguide.ropensci.org/ (and don't hesitate to ask if you have any questions). 

So! Let me know what kind of post you'd like to write and what kind of timeline you want to follow. You can reach me on the Slack (Steffi LaZerte; you should have gotten an invitation by now?) or via email ([sel@steffilazerte.ca](mailto:sel@steffilazerte.ca)), and/or ping me when you open the PR to roweb3 (@steffilazerte). 

Thanks!

**Comment by RonaldVisser** [comment]
Hi @steffilazerte ,

Thanks for the comments! I'll have a more through look at the documentation and I'll probably email you with questions later. I have not received a Slack-invite, but I have not used that for some time... 

Thank you :)
